# Generated by Django 4.2.13 on 2026-08-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0005_appointment_payment_preference'),
        ('lab', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='labreport',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='appointment_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='choice_made_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='choice_made_by',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('nurse', 'Nurse')], max_length=10),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='patient_choice',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_house', 'In-House'), ('outside', 'Outside')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='payment_preference',
            field=models.CharField(blank=True, choices=[('pay_online', 'Pay Online'), ('pay_at_lab', 'Pay at Lab')], max_length=15),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending_online', 'Pending Online Payment'), ('paid', 'Paid')], default='unpaid', max_length=15),
        ),
        # NOTE: encounter used to point at apps.clinical.Encounter (legacy,
        # dead scaffolding — see apps/opd/views.py:568-572 — nothing in the
        # app ever wrote a row there or to lab_request via it). Its PK is a
        # bigint; OPDEncounter's PK is a uuid. There is no valid cast from
        # one to the other, so instead of ALTER COLUMN ... TYPE uuid (which
        # fails outright), the column is dropped and recreated pointing at
        # the live table. Safe because lab_request has never had a working
        # write path before this feature, so there's nothing to preserve.
        migrations.RemoveField(
            model_name='labrequest',
            name='encounter',
        ),
        migrations.AddField(
            model_name='labrequest',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_requests', to='opd.opdencounter'),
        ),
    ]
