# Generated by Django 4.2.13 on 2026-08-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_labreport_file_name_labreport_mime_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending_online', 'Pending Online Payment'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=15),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('collected', 'Sample Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='ordered', max_length=20),
        ),
    ]
