# Generated by Django 4.2.13 on 2026-08-17 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_invoice_encounter'),
        ('lab', '0004_alter_labreport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='request_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['request_number'], name='lab_request_request_ccac3a_idx'),
        ),
    ]
