# Generated by Django 4.2.13 on 2026-09-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_labrequest_invoice_labrequest_request_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='sample_type',
            field=models.CharField(default='blood', max_length=20),
        ),
    ]
