# Generated by hand for Atomwalk HMS (Django 4.2.13 migration style) —
# NOT run against a live database in this session (no reachable Postgres
# instance from the build environment). Run `python manage.py migrate`
# against each tenant DB before relying on this.

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("org", "0019_nursedoctorassignment_and_more"),
        ("patients", "0007_patient_guardian_awpid_patient_guardian_mobile_and_more"),
        ("opd", "0009_prescription_choice_made_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionReferral",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("admission_type", models.CharField(max_length=30)),
                ("admission_source", models.CharField(max_length=30)),
                ("reason_for_admission", models.TextField()),
                ("recommended_at", models.DateTimeField(auto_now_add=True)),
                ("external_referring_doctor_name", models.CharField(blank=True, max_length=200)),
                ("external_referring_facility", models.CharField(blank=True, max_length=200)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("source_details", models.JSONField(blank=True, default=dict)),
                ("is_mlc", models.BooleanField(default=False)),
                ("guardian_consent_by", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("converted", "Converted"), ("withdrawn", "Withdrawn")], db_index=True, default="pending", max_length=12)),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="admission_referrals", to="patients.patient")),
                ("department", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="admission_referrals", to="org.department")),
                ("source_appointment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="admission_referrals", to="opd.appointment")),
                ("source_encounter", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="admission_referrals", to="opd.opdencounter")),
                ("recommended_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="admission_referrals_made", to="org.staffuser")),
                ("accepted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="admission_referrals_accepted", to="org.staffuser")),
            ],
            options={
                "db_table": "admission_referral",
                "ordering": ["-recommended_at"],
            },
        ),
        migrations.CreateModel(
            name="Admission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("admission_number", models.CharField(max_length=20, unique=True)),
                ("admission_type", models.CharField(max_length=30)),
                ("admission_source", models.CharField(max_length=30)),
                ("reason_for_admission", models.TextField()),
                ("expected_discharge_date", models.DateField(blank=True, null=True)),
                ("attendant_name", models.CharField(blank=True, max_length=200)),
                ("attendant_phone", models.CharField(blank=True, max_length=15)),
                ("payer_type", models.CharField(blank=True, max_length=20)),
                ("insurance_provider", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(choices=[("requested", "Requested"), ("admitted", "Admitted (awaiting bed)"), ("active", "Active"), ("discharge_initiated", "Discharge Initiated"), ("discharged", "Discharged"), ("cancelled", "Cancelled")], db_index=True, default="requested", max_length=22)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="admissions", to="org.branch")),
                ("referral", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="admission", to="ipd.admissionreferral")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="admissions", to="patients.patient")),
                ("department", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="admissions", to="org.department")),
                ("ordering_doctor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="admissions_ordered", to="org.staffuser")),
                ("logged_by_staff", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="admissions_logged", to="org.staffuser")),
                ("previous_admission", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="readmissions", to="ipd.admission")),
            ],
            options={
                "db_table": "admission",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdmissionDeposit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("payment_mode", models.CharField(max_length=50)),
                ("transaction_ref", models.CharField(blank=True, max_length=100)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                ("admission", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="deposits", to="ipd.admission")),
                ("collected_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="org.staffuser")),
            ],
            options={
                "db_table": "admission_deposit",
                "ordering": ["-collected_at"],
            },
        ),
        migrations.AddIndex(
            model_name="admission",
            index=models.Index(fields=["status", "branch"], name="ipd_admissi_status_9e6f21_idx"),
        ),
        migrations.AddIndex(
            model_name="admission",
            index=models.Index(fields=["patient", "status"], name="ipd_admissi_patient_3ab7c4_idx"),
        ),
    ]
