# Generated by hand — NOT run against a live database in this session.
#
# Seeds the two new OptionList catalogs (admission_type, admission_source)
# as is_system=True defaults — a hospital admin can deactivate any of these
# ("make it configurable") but not delete them, same as every other
# OptionList seed in this codebase. Also seeds one NextNumber(entity=
# "admission") row per existing Branch — NNTM's get_next_number() does a
# plain .get() with no fallback, so a branch with no row for this entity
# would 500 the first time front desk tries to complete a registration.

from django.db import migrations


ADMISSION_TYPES = [
    ("emergency", "Emergency"),
    ("urgent", "Urgent"),
    ("elective", "Elective"),
    ("day_care", "Day Care"),
    ("newborn", "Newborn"),
]

ADMISSION_SOURCES = [
    ("opd_consultation", "OPD Consultation"),
    ("external_referral", "External Referral"),
    ("walk_in", "Walk-in"),
    ("direct_order", "Direct / Physician Order"),
    ("transfer_in", "Transfer-in"),
    ("ambulance_ems", "Ambulance / EMS"),
    ("tpa_cashless", "Insurance / TPA-coordinated"),
    ("medical_tourism", "Medical Tourism"),
    ("telemedicine", "Telemedicine"),
    ("involuntary_mlc", "Involuntary / MLC"),
]


def seed_catalogs(apps, schema_editor):
    OptionList = apps.get_model("billing", "OptionList")
    db = schema_editor.connection.alias

    for i, (value, label) in enumerate(ADMISSION_TYPES):
        OptionList.objects.using(db).get_or_create(
            list_type="admission_type", value=value,
            defaults={"label": label, "is_active": True, "is_system": True, "sort_order": i},
        )
    for i, (value, label) in enumerate(ADMISSION_SOURCES):
        OptionList.objects.using(db).get_or_create(
            list_type="admission_source", value=value,
            defaults={"label": label, "is_active": True, "is_system": True, "sort_order": i},
        )


def unseed_catalogs(apps, schema_editor):
    OptionList = apps.get_model("billing", "OptionList")
    db = schema_editor.connection.alias
    OptionList.objects.using(db).filter(list_type__in=["admission_type", "admission_source"]).delete()


def seed_next_numbers(apps, schema_editor):
    Branch = apps.get_model("org", "Branch")
    NextNumber = apps.get_model("org", "NextNumber")
    db = schema_editor.connection.alias

    for branch in Branch.objects.using(db).all():
        NextNumber.objects.using(db).get_or_create(
            branch_id=branch.id, entity="admission",
            defaults={"prefix": "ADM-", "last_number": 0, "pad_length": 6},
        )


def unseed_next_numbers(apps, schema_editor):
    NextNumber = apps.get_model("org", "NextNumber")
    db = schema_editor.connection.alias
    NextNumber.objects.using(db).filter(entity="admission").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ipd", "0001_initial"),
        ("billing", "0009_remove_old_option_tables"),
        ("org", "0019_nursedoctorassignment_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_catalogs, unseed_catalogs),
        migrations.RunPython(seed_next_numbers, unseed_next_numbers),
    ]
