# Generated by Django 4.2.13 on 2026-09-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0002_seed_admission_catalogs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='admission',
            new_name='admission_status_ddd06d_idx',
            old_name='ipd_admissi_status_9e6f21_idx',
        ),
        migrations.RenameIndex(
            model_name='admission',
            new_name='admission_patient_961251_idx',
            old_name='ipd_admissi_patient_3ab7c4_idx',
        ),
    ]
