# Generated by Django 4.2.13 on 2026-09-15 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0020_ward_bed'),
        ('ipd', '0003_rename_ipd_admissi_status_9e6f21_idx_admission_status_ddd06d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='org.bed'),
        ),
        migrations.AddField(
            model_name='admission',
            name='bed_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
