# Generated by hand — NOT run against a live database in this session
# (no DB reachable from here; run `python manage.py migrate_tenants` after
# pulling this change).
#
# The real "it actually happened now" discharge timestamp, set once by
# views.DischargeAdmissionView — distinct from expected_discharge_date
# (an estimate, editable any time before then via AdmissionDetailView's
# new PATCH). See Admission.discharged_at's own field comment.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0004_admission_bed_admission_bed_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='discharged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
