# Generated by hand — NOT run against a live database in this session
# (no DB reachable from here; run `python manage.py migrate_tenants` after
# pulling this change).
#
# Closes the reconciliation gap AdmissionDeposit's own docstring used to
# call "Phase 2, not built here" — views.GenerateInvoiceView sets this the
# moment a deposit is folded into a real billing.Invoice as a
# billing.Payment, so a later invoice-generation call for the same
# admission never applies the same deposit twice. Depends on billing's
# 0018 (not because this FK needs daily_rate specifically, just to land
# after billing's model state is fully settled for this round of changes).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0005_admission_discharged_at'),
        ('billing', '0018_optionlist_daily_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissiondeposit',
            name='reconciled_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_ipd_deposits', to='billing.invoice'),
        ),
    ]
