# Generated by hand — NOT run against a live database in this session
# (no DB reachable from here; run `python manage.py migrate_tenants` after
# pulling this change).
#
# Supports the front-desk-can-log-an-external-referral-letter change (see
# models.AdmissionReferral module docstring, design decision 2, and
# views.RegisterExternalReferralView) — purely descriptive, changes no
# enforcement, so a plain AddField with a default is safe against existing
# rows (every row that predates this migration was doctor-recommended, so
# False is the correct backfilled value, not just a placeholder).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0006_admissiondeposit_reconciled_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionreferral',
            name='front_desk_logged',
            field=models.BooleanField(default=False),
        ),
    ]
