# Generated by Django 4.2.13 on 2026-09-17 09:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0029_bed_reserved_for_admission_id_alter_bed_status'),
        ('ipd', '0007_admissionreferral_front_desk_logged'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('initial_assignment', 'Initial Bed Assignment'), ('transfer', 'Bed Transfer'), ('release', 'Bed Released (no discharge)'), ('discharge', 'Discharge')], max_length=20)),
                ('from_room_name', models.CharField(blank=True, max_length=100)),
                ('from_bed_number', models.CharField(blank=True, max_length=20)),
                ('to_room_name', models.CharField(blank=True, max_length=100)),
                ('to_bed_number', models.CharField(blank=True, max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='ipd.admission')),
                ('from_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='org.bed')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_movements_recorded', to='org.staffuser')),
                ('to_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='org.bed')),
            ],
            options={
                'db_table': 'patient_movement',
                'ordering': ['-moved_at'],
            },
        ),
    ]
