"""
apps/lab/pdf.py
---------------
Renders a lab report to a printable PDF for the My Reports vault when the
lab uploaded no file of its own (only result_summary + parameter rows).
Same reportlab pattern as apps/opd/pdf.py.

Kept deliberately simple — this is a patient-facing copy of an already
released result, not the lab's own report format.
"""

import io

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas


def _wrap(text, width):
    words = str(text or "").split()
    lines, cur = [], ""
    for w in words:
        if len(cur) + len(w) + 1 <= width:
            cur = (cur + " " + w).strip()
        else:
            if cur:
                lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines


def generate_lab_report_pdf(*, report, items, patient, branch, hospital_name,
                            test_name="Lab Report", qr_token=None):
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    W, H = A4
    left = 20 * mm
    right = W - 20 * mm

    c.setFont("Helvetica-Bold", 18)
    c.drawString(left, H - 20 * mm, hospital_name or "Hospital")
    if branch:
        bits = [p for p in [getattr(branch, "address", ""), getattr(branch, "city", ""),
                            getattr(branch, "state", ""), getattr(branch, "pincode", "")] if p]
        if bits:
            c.setFont("Helvetica", 9)
            c.drawString(left, H - 26 * mm, ", ".join(bits))

    header_right = right
    if qr_token:
        try:
            import qrcode
            qr = qrcode.QRCode(box_size=4, border=1)
            qr.add_data(qr_token)
            qr.make(fit=True)
            qbuf = io.BytesIO()
            qr.make_image(fill_color="black", back_color="white").save(qbuf, format="PNG")
            qbuf.seek(0)
            s = 20 * mm
            c.drawImage(ImageReader(qbuf), right - s, H - 20 * mm - s + 4 * mm,
                        width=s, height=s, mask="auto")
            c.setFont("Helvetica", 6)
            c.drawCentredString(right - s / 2, H - 20 * mm - s + 1 * mm, "Scan to save in My Reports")
            header_right = right - s - 4 * mm
        except Exception:
            header_right = right

    c.setFont("Helvetica-Bold", 14)
    c.drawRightString(header_right, H - 20 * mm, "LAB REPORT")
    c.setFont("Helvetica", 9)
    c.drawRightString(header_right, H - 26 * mm, f"Report #: {report.report_number or str(report.id)}")
    if report.delivered_at:
        c.drawRightString(header_right, H - 31 * mm, f"Date: {report.delivered_at.strftime('%d %b %Y')}")

    y = H - 44 * mm
    c.setStrokeColor(colors.HexColor("#DDDDDD"))
    c.line(left, y, right, y)
    y -= 9 * mm

    c.setFont("Helvetica-Bold", 12)
    c.drawString(left, y, test_name or "Lab Report")
    y -= 7 * mm
    if patient:
        c.setFont("Helvetica", 9)
        c.drawString(left, y, f"Patient: {getattr(patient, 'full_name', '')}    "
                              f"UHID: {getattr(patient, 'uhid', '')}")
        y -= 9 * mm

    # parameter table
    c.setFillColor(colors.HexColor("#F5F5F0"))
    c.rect(left, y - 6 * mm, right - left, 8 * mm, fill=1, stroke=0)
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(left + 2 * mm, y - 4 * mm, "Parameter")
    c.drawString(left + 72 * mm, y - 4 * mm, "Result")
    c.drawString(left + 108 * mm, y - 4 * mm, "Unit")
    c.drawString(left + 130 * mm, y - 4 * mm, "Reference")
    c.drawRightString(right, y - 4 * mm, "Flag")
    y -= 12 * mm

    c.setFont("Helvetica", 9)
    for it in items:
        if y < 30 * mm:
            c.showPage()
            y = H - 25 * mm
            c.setFont("Helvetica", 9)
        c.drawString(left + 2 * mm, y, str(it.parameter_name or "")[:40])
        c.drawString(left + 72 * mm, y, str(it.result_value or ""))
        c.drawString(left + 108 * mm, y, str(it.unit or ""))
        c.drawString(left + 130 * mm, y, str(it.reference_range or "")[:20])
        if it.is_abnormal:
            c.setFillColor(colors.HexColor("#B42318"))
            c.drawRightString(right, y, "Abnormal")
            c.setFillColor(colors.black)
        y -= 6 * mm

    if report.result_summary:
        y -= 6 * mm
        c.setFont("Helvetica-Bold", 9)
        c.drawString(left, y, "Summary")
        y -= 5 * mm
        c.setFont("Helvetica", 9)
        for line in _wrap(report.result_summary, 110):
            if y < 25 * mm:
                c.showPage()
                y = H - 25 * mm
            c.drawString(left, y, line)
            y -= 5 * mm

    c.setFont("Helvetica-Oblique", 7)
    c.setFillColor(colors.HexColor("#888888"))
    c.drawString(left, 15 * mm, "Patient copy of a released lab result — generated by the HMS.")
    c.save()
    return buf.getvalue()
