# Generated by Django 4.2.13 on 2026-09-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='task',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskAssignment',
        ),
    ]
