"""
apps/prescriptions/models.py
----------------------------
Tables: Drug (catalog), Prescription, PrescriptionItem

Maps to FHIR MedicationRequest (per item).
On prescription.finalize() signal writes to registry.SharedPrescription.
"""

from django.db import models
from apps.org.models import StaffUser
from apps.patients.models import Patient
from apps.clinical.models import Encounter


class Drug(models.Model):
    """
    Hospital drug catalog. Tenant-managed.
    drug_code is the internal code (not a standard code — optional).
    """
    FORM_CHOICES = [
        ("tablet",     "Tablet"),
        ("capsule",    "Capsule"),
        ("syrup",      "Syrup"),
        ("injection",  "Injection"),
        ("drops",      "Drops"),
        ("cream",      "Cream / Ointment"),
        ("inhaler",    "Inhaler"),
        ("patch",      "Patch"),
        ("other",      "Other"),
    ]

    name        = models.CharField(max_length=200)
    generic_name= models.CharField(max_length=200, blank=True)
    drug_code   = models.CharField(max_length=50, blank=True)
    form        = models.CharField(max_length=20, choices=FORM_CHOICES, default="tablet")
    strength    = models.CharField(max_length=50, blank=True)   # e.g. "500mg"
    unit        = models.CharField(max_length=20, default="mg")
    is_active   = models.BooleanField(default=True)
    created_at  = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "prescriptions"
        db_table  = "drug"
        ordering  = ["name"]

    def __str__(self):
        return f"{self.name} {self.strength}"


class Prescription(models.Model):
    """
    Prescription header. Items are PrescriptionItem rows.
    rx_number generated by NNTM (entity="RX").
    """
    STATUS_CHOICES = [
        ("draft",     "Draft"),
        ("finalized", "Finalized"),
        ("dispensed", "Dispensed"),
    ]

    patient         = models.ForeignKey(Patient, on_delete=models.PROTECT,
                                        related_name="prescriptions")
    encounter       = models.ForeignKey(Encounter, on_delete=models.PROTECT,
                                        related_name="prescriptions")
    prescribed_by   = models.ForeignKey(StaffUser, on_delete=models.PROTECT,
                                        related_name="prescriptions",
                                        limit_choices_to={"role": "doctor"})
    rx_number       = models.CharField(max_length=30, unique=True)
    status          = models.CharField(max_length=20, choices=STATUS_CHOICES, default="draft", db_index=True)
    notes           = models.TextField(blank=True)
    finalized_at    = models.DateTimeField(null=True, blank=True)
    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

    class Meta:
        app_label = "prescriptions"
        db_table  = "prescription"

    def __str__(self):
        return f"{self.rx_number} — {self.patient.uhid}"


class PrescriptionItem(models.Model):
    """One drug line item in a prescription. Maps to FHIR MedicationRequest."""
    prescription    = models.ForeignKey(Prescription, on_delete=models.CASCADE,
                                        related_name="items")
    drug            = models.ForeignKey(Drug, on_delete=models.PROTECT,
                                        null=True, blank=True)
    drug_name       = models.CharField(max_length=200)  # denormalized for free-text entry
    dose            = models.CharField(max_length=50, blank=True)
    unit            = models.CharField(max_length=20, blank=True)
    frequency       = models.CharField(max_length=50, blank=True)   # e.g. "1-0-1"
    route           = models.CharField(max_length=50, blank=True)   # e.g. "Oral"
    duration_days   = models.PositiveSmallIntegerField(null=True, blank=True)
    instructions    = models.TextField(blank=True)  # "take after food", etc.
    order           = models.PositiveSmallIntegerField(default=0)   # display order

    class Meta:
        app_label = "prescriptions"
        db_table  = "prescription_item"
        ordering  = ["order"]

    def __str__(self):
        return f"{self.drug_name} {self.dose}"
