# Generated by Django 4.2.13 on 2026-07-31 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('transcription', 'Transcription'), ('soap_notes', 'SOAP Note Extraction'), ('diagnosis_suggest', 'Diagnosis Suggestion'), ('rx_suggest', 'Prescription Suggestion')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('output', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='clinical.encounter')),
            ],
            options={
                'db_table': 'ai_job',
            },
        ),
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.TextField()),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued for Processing'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='clinical.encounter')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.staffuser')),
            ],
            options={
                'db_table': 'voice_recording',
            },
        ),
        migrations.CreateModel(
            name='SuggestionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(max_length=50)),
                ('suggested_value', models.JSONField()),
                ('final_value', models.JSONField(blank=True, null=True)),
                ('action', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('modified', 'Modified and Accepted')], max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.PROTECT, to='org.staffuser')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_audits', to='clinical.encounter')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_audits', to='ai_pipeline.aijob')),
            ],
            options={
                'db_table': 'suggestion_audit',
            },
        ),
        migrations.AddField(
            model_name='aijob',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ai_pipeline.voicerecording'),
        ),
    ]
