# Generated by Django 4.2.13 on 2026-08-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aijob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued for Processing'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20),
        ),
    ]
