# Generated by Django 4.2.13 on 2026-08-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pipeline', '0002_alter_aijob_status_alter_voicerecording_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestionaudit',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='suggestionaudit',
            name='encounter',
        ),
        migrations.RemoveField(
            model_name='suggestionaudit',
            name='job',
        ),
        migrations.RemoveField(
            model_name='voicerecording',
            name='encounter',
        ),
        migrations.RemoveField(
            model_name='voicerecording',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='AIJob',
        ),
        migrations.DeleteModel(
            name='SuggestionAudit',
        ),
        migrations.DeleteModel(
            name='VoiceRecording',
        ),
    ]
