# Generated by Django 4.2.13 on 2026-08-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_seed_billing_dropdowns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='encounter',
        ),
    ]
