# Generated by hand — NOT run against a live database in this session
# (no DB reachable from here; run `python manage.py migrate_tenants` after
# pulling this change — see apps/ipd/migrations/0002_seed_admission_catalogs.py
# for the identical pattern this follows).
#
# Seeds OptionList(list_type="room_type") with the three values org.Room
# used to hard-code via ROOM_TYPE_CHOICES, as is_system=True defaults — a
# hospital admin can deactivate any of these or add their own (e.g. "OT",
# "Lab") from the new Room Types setting on the Rooms & Floors page, but
# can't delete the seeded ones, same as every other OptionList seed here.
# Every existing Room row's room_type already matches one of these three
# values, so no data migration on Room itself is needed.

from django.db import migrations

ROOM_TYPES = [
    ("consultation", "Consultation"),
    ("procedure",    "Procedure"),
    ("other",        "Other"),
]


def seed_room_types(apps, schema_editor):
    OptionList = apps.get_model("billing", "OptionList")
    db = schema_editor.connection.alias
    for i, (value, label) in enumerate(ROOM_TYPES):
        OptionList.objects.using(db).get_or_create(
            list_type="room_type", value=value,
            defaults={"label": label, "is_active": True, "is_system": True, "sort_order": i},
        )


def unseed_room_types(apps, schema_editor):
    OptionList = apps.get_model("billing", "OptionList")
    db = schema_editor.connection.alias
    OptionList.objects.using(db).filter(list_type="room_type").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0011_optionlist_room_type_choice"),
    ]

    operations = [
        migrations.RunPython(seed_room_types, unseed_room_types),
    ]
