# Generated by hand — NOT run against a live database in this session
# (no DB reachable from here; run `python manage.py migrate_tenants` after
# pulling this change).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_seed_room_type_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionlist',
            name='list_type',
            field=models.CharField(choices=[('service_category', 'Service Category'), ('payment_mode', 'Payment Mode'), ('invoice_status', 'Invoice Status'), ('drug_form', 'Drug Form'), ('admission_type', 'Admission Type'), ('admission_source', 'Admission Source'), ('room_type', 'Room Type'), ('ward_type', 'Ward Type')], db_index=True, max_length=20),
        ),
    ]
