# Generated by hand — NOT run against a live database in this session
# (no DB reachable from here; run `python manage.py migrate_tenants` after
# pulling this change — see 0012_seed_room_type_catalog.py for the
# identical pattern this follows).
#
# Seeds OptionList(list_type="ward_type") with the seven values org.Ward
# used to hard-code via WARD_TYPE_CHOICES, as is_system=True defaults — a
# hospital admin can deactivate any of these or add their own (e.g. "NICU",
# "Maternity") from the new Ward Types setting on the Rooms & Floors page,
# but can't delete the seeded ones, same as every other OptionList seed here.
# Every existing Ward row's ward_type already matches one of these seven
# values, so no data migration on Ward itself is needed.

from django.db import migrations

WARD_TYPES = [
    ("general",      "General"),
    ("private",      "Private"),
    ("semi_private",  "Semi-Private"),
    ("icu",          "ICU"),
    ("hdu",          "HDU"),
    ("isolation",    "Isolation"),
    ("other",        "Other"),
]


def seed_ward_types(apps, schema_editor):
    OptionList = apps.get_model("billing", "OptionList")
    db = schema_editor.connection.alias
    for i, (value, label) in enumerate(WARD_TYPES):
        OptionList.objects.using(db).get_or_create(
            list_type="ward_type", value=value,
            defaults={"label": label, "is_active": True, "is_system": True, "sort_order": i},
        )


def unseed_ward_types(apps, schema_editor):
    OptionList = apps.get_model("billing", "OptionList")
    db = schema_editor.connection.alias
    OptionList.objects.using(db).filter(list_type="ward_type").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_optionlist_ward_type_choice"),
    ]

    operations = [
        migrations.RunPython(seed_ward_types, unseed_ward_types),
    ]
