# Generated by hand — NOT run against a live database in this session
# (no DB reachable from here; run `python manage.py migrate_tenants` after
# pulling this change).
#
# Adds the two fields that let a single "room_type" OptionList catalog
# describe both OPD rooms and bed-based IPD rooms (wards/ICU/etc.) — see
# OptionList's own docstring for the v8 unification this is part of.
# Meaningless (left blank/False) for every other list_type.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_seed_ward_type_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionlist',
            name='category',
            field=models.CharField(blank=True, choices=[('opd', 'OPD'), ('ipd', 'IPD'), ('procedure', 'Procedure'), ('other', 'Other')], max_length=12),
        ),
        migrations.AddField(
            model_name='optionlist',
            name='is_bed_based',
            field=models.BooleanField(default=False),
        ),
    ]
