# Generated by hand — NOT run against a live database in this session
# (no DB reachable from here; run `python manage.py migrate_tenants` after
# pulling this change — see 0012_seed_room_type_catalog.py for the general
# pattern this follows).
#
# Data migration for the v8 unification (org.Ward folded into org.Room —
# see org.Room's own docstring). Three things happen here:
#
#   1. The three original room_type rows (consultation/procedure/other)
#      get category/is_bed_based flags so the frontend can group them —
#      none of them are bed-based.
#   2. Every existing ward_type row (general/private/semi_private/icu/hdu/
#      isolation/other) gets a corresponding room_type row created —
#      is_bed_based=True, category="ipd" — so a Room can carry the exact
#      same "General Ward"/"ICU"/etc. label a Ward used to. "other" is
#      remapped to value "ward_other" (label "Other (Ward)") instead of
#      colliding with the OPD "other" row already in room_type, which
#      must stay non-bed-based.
#   3. The ward_type rows themselves are deleted — nothing reads
#      list_type="ward_type" once org 0027 has copied every Ward's
#      ward_type across using this same value mapping (kept in sync by
#      hand — see WARD_TO_ROOM_TYPE_VALUE below and its twin in
#      apps/org/migrations/0027_migrate_wards_to_rooms_and_beds.py).

from django.db import migrations

# Kept identical to the mapping in
# apps/org/migrations/0027_migrate_wards_to_rooms_and_beds.py — both must
# agree on where each ward_type value ends up in room_type.
WARD_TO_ROOM_TYPE_VALUE = {
    "general":      "general",
    "private":      "private",
    "semi_private": "semi_private",
    "icu":          "icu",
    "hdu":          "hdu",
    "isolation":    "isolation",
    "other":        "ward_other",
}
WARD_OTHER_LABEL = "Other (Ward)"


def merge_forward(apps, schema_editor):
    OptionList = apps.get_model("billing", "OptionList")
    db = schema_editor.connection.alias

    OptionList.objects.using(db).filter(
        list_type="room_type", value__in=["consultation", "procedure"],
    ).update(category="opd", is_bed_based=False)
    OptionList.objects.using(db).filter(
        list_type="room_type", value="other",
    ).update(category="other", is_bed_based=False)

    ward_rows = list(OptionList.objects.using(db).filter(list_type="ward_type"))
    for row in ward_rows:
        room_value = WARD_TO_ROOM_TYPE_VALUE.get(row.value, row.value)
        label = WARD_OTHER_LABEL if row.value == "other" else row.label
        OptionList.objects.using(db).get_or_create(
            list_type="room_type", value=room_value,
            defaults={
                "label": label, "is_active": row.is_active, "is_system": True,
                "sort_order": 100 + row.sort_order, "category": "ipd", "is_bed_based": True,
            },
        )

    OptionList.objects.using(db).filter(list_type="ward_type").delete()


def merge_backward(apps, schema_editor):
    # Best-effort only — recreates the ward_type rows this migration
    # deleted; doesn't attempt to remove the room_type rows created above
    # (org 0027's own reverse doesn't delete the Rooms it created from
    # Wards either, for the same "don't destroy data on a routine rollback"
    # reasoning).
    OptionList = apps.get_model("billing", "OptionList")
    db = schema_editor.connection.alias
    defaults = [
        ("general",      "General"),
        ("private",      "Private"),
        ("semi_private", "Semi-Private"),
        ("icu",          "ICU"),
        ("hdu",          "HDU"),
        ("isolation",    "Isolation"),
        ("other",        "Other"),
    ]
    for i, (value, label) in enumerate(defaults):
        OptionList.objects.using(db).get_or_create(
            list_type="ward_type", value=value,
            defaults={"label": label, "is_active": True, "is_system": True, "sort_order": i},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_optionlist_category_is_bed_based'),
    ]

    operations = [
        migrations.RunPython(merge_forward, merge_backward),
    ]
