# Generated by hand — NOT run against a live database in this session
# (no DB reachable from here; run `python manage.py migrate_tenants` after
# pulling this change).
#
# list_type="ward_type" no longer exists as of 0016's data migration — this
# just drops it from the CharField's choices= to match, same pattern as
# 0022_room_type_drop_choices.py in apps/org used when Room.room_type's
# choices= list was retired in favor of the OptionList catalog.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_merge_ward_types_into_room_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionlist',
            name='list_type',
            field=models.CharField(choices=[('service_category', 'Service Category'), ('payment_mode', 'Payment Mode'), ('invoice_status', 'Invoice Status'), ('drug_form', 'Drug Form'), ('admission_type', 'Admission Type'), ('admission_source', 'Admission Source'), ('room_type', 'Room Type')], db_index=True, max_length=20),
        ),
    ]
