# Generated by hand — NOT run against a live database in this session
# (no DB reachable from here; run `python manage.py migrate_tenants` after
# pulling this change).
#
# Adds the per-night rate a "room_type" OptionList row bills against —
# apps.ipd.views.GenerateInvoiceView reads it (nights stayed x this) to
# price an admission's room charges. Meaningless (left null) for every
# other list_type, and for a room_type row that isn't is_bed_based.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_optionlist_drop_ward_type_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionlist',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
