# Generated by Django 4.2.13 on 2026-09-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_optionlist_daily_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionlist',
            name='list_type',
            field=models.CharField(choices=[('service_category', 'Service Category'), ('payment_mode', 'Payment Mode'), ('invoice_status', 'Invoice Status'), ('drug_form', 'Drug Form'), ('admission_type', 'Admission Type'), ('admission_source', 'Admission Source'), ('room_type', 'Room Type'), ('sample_type', 'Sample Type'), ('appointment_type', 'Appointment Type')], db_index=True, max_length=20),
        ),
    ]
