# Generated by Django 4.2.13 on 2026-07-31 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0002_patientidentity_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('mobile_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patient_identity',
            },
        ),
        migrations.CreateModel(
            name='SharedAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30)),
                ('substance', models.CharField(max_length=200)),
                ('reaction', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('source_tenant_id', models.IntegerField()),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shared_allergy',
            },
        ),
        migrations.CreateModel(
            name='SharedDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30)),
                ('icd10_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('clinical_status', models.CharField(default='active', max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('source_tenant_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shared_diagnosis',
            },
        ),
        migrations.CreateModel(
            name='SharedLabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30)),
                ('test_name', models.CharField(max_length=200)),
                ('result_summary', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('delivered_at', models.DateTimeField()),
                ('source_tenant_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shared_lab_result',
            },
        ),
        migrations.CreateModel(
            name='SharedPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30)),
                ('prescribed_on', models.DateField()),
                ('source_tenant_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shared_prescription',
            },
        ),
        migrations.CreateModel(
            name='SharedVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30)),
                ('recorded_at', models.DateTimeField()),
                ('source', models.CharField(default='clinic', max_length=20)),
                ('bp_systolic', models.SmallIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.SmallIntegerField(blank=True, null=True)),
                ('pulse_rate', models.SmallIntegerField(blank=True, null=True)),
                ('spo2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('resp_rate', models.SmallIntegerField(blank=True, null=True)),
                ('blood_sugar_mgdl', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('source_tenant_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shared_vital',
            },
        ),
        migrations.CreateModel(
            name='SharedPrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('dose', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('route', models.CharField(blank=True, max_length=50)),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='registry.sharedprescription')),
            ],
            options={
                'db_table': 'shared_prescription_item',
            },
        ),
    ]
