# Generated by Django 4.2.13 on 2026-08-03 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_staffemailindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient_account',
            },
        ),
        migrations.AlterField(
            model_name='staffemailindex',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PortalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField()),
                ('db_name', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=200)),
                ('appointment_id', models.UUIDField()),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('scheduled_date', models.DateField()),
                ('chief_complaint', models.TextField(blank=True)),
                ('status', models.CharField(default='scheduled', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='registry.patientaccount')),
            ],
            options={
                'db_table': 'portal_booking',
                'ordering': ['-created_at'],
            },
        ),
    ]
