# Generated by Django 4.2.13 on 2026-08-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_blacklistedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('lab_report', 'Lab Report'), ('prescription', 'Prescription'), ('scan', 'Scan / Imaging'), ('discharge_summary', 'Discharge Summary'), ('other', 'Other')], default='other', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_data', models.TextField()),
                ('uploaded_by', models.CharField(choices=[('patient', 'Patient'), ('staff', 'Staff')], default='patient', max_length=10)),
                ('source_tenant_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shared_document',
            },
        ),
    ]
