# Generated by Django 4.2.13 on 2026-08-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_shareddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddocument',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sharedlabresult',
            name='file_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sharedlabresult',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
