# Generated by Django 4.2.13 on 2026-08-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_shareddocument_source_ref_sharedlabresult_file_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientidentity',
            name='guardian_mobile_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='patientidentity',
            name='is_dependent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientidentity',
            name='mobile_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PatientRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_awpid', models.CharField(db_index=True, max_length=30)),
                ('guardian_awpid', models.CharField(db_index=True, max_length=30)),
                ('relationship', models.CharField(choices=[('child', 'Child'), ('parent', 'Parent'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('ward', 'Ward'), ('other', 'Other')], default='other', max_length=20)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patient_relationship',
                'unique_together': {('dependent_awpid', 'guardian_awpid')},
            },
        ),
    ]
