# Generated by Django 4.2.13 on 2026-08-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_patientidentity_guardian_mobile_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalbooking',
            name='patient_awpid',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='portalbooking',
            name='patient_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
