# Generated by Django 4.2.13 on 2026-08-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_portalbooking_patient_awpid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaccount',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
