# Generated by Django 4.2.13 on 2026-08-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_patientaccount_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaccount',
            name='photo',
            field=models.TextField(blank=True),
        ),
    ]
