# Generated by Django 4.2.13 on 2026-08-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_patientaccount_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMobileIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(db_index=True, max_length=15, unique=True)),
                ('tenant_id', models.IntegerField()),
                ('db_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff_mobile_index',
            },
        ),
        migrations.AlterField(
            model_name='patientaccount',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patientaccount',
            name='mobile',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
