# Generated by Django 4.2.13 on 2026-08-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_staffmobileindex_alter_patientaccount_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalbooking',
            name='db_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='portalbooking',
            name='status',
            field=models.CharField(db_index=True, default='scheduled', max_length=15),
        ),
        migrations.AlterField(
            model_name='portalbooking',
            name='tenant_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
