# Generated by Django 4.2.13 on 2026-08-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_alter_portalbooking_db_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('scheduled_label', models.CharField(blank=True, max_length=50)),
                ('administered_date', models.DateField()),
                ('source', models.CharField(choices=[('clinic', 'Clinic administered'), ('self_reported', 'Self reported')], default='clinic', max_length=20)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('pending_review', 'Pending review'), ('rejected', 'Rejected')], db_index=True, default='verified', max_length=20)),
                ('verified_by_name', models.CharField(blank=True, max_length=200)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_data', models.TextField(blank=True)),
                ('source_tenant_id', models.IntegerField(blank=True, null=True)),
                ('recorded_by', models.CharField(default='patient', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shared_vaccination',
                'ordering': ['administered_date'],
                'indexes': [models.Index(fields=['awpid', 'verification_status'], name='shared_vacc_awpid_772b77_idx')],
            },
        ),
    ]
