# Generated by Django 4.2.13 on 2026-08-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_sharedvaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmobileindex',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
    ]
