# Generated by Django 4.2.13 on 2026-08-11 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_staffmobileindex_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('owner_tenant_id', models.IntegerField(blank=True, null=True)),
                ('is_template', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vaccination_schedule',
            },
        ),
        migrations.CreateModel(
            name='VaccinationScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('dose_number', models.PositiveIntegerField(default=1)),
                ('scheduled_label', models.CharField(max_length=50)),
                ('min_age_days', models.PositiveIntegerField()),
                ('max_age_days', models.PositiveIntegerField(blank=True, null=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='registry.vaccinationschedule')),
            ],
            options={
                'db_table': 'vaccination_schedule_rule',
                'ordering': ['sort_order'],
            },
        ),
    ]
