# Generated by Django 4.2.13 on 2026-08-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_seed_default_vaccination_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedvaccination',
            name='dose_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedvaccination',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedvaccination',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sharedvaccination',
            name='administered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sharedvaccination',
            name='source',
            field=models.CharField(choices=[('clinic', 'Clinic administered'), ('self_reported', 'Self reported'), ('doctor_ordered', 'Doctor ordered')], default='clinic', max_length=20),
        ),
        migrations.AlterField(
            model_name='sharedvaccination',
            name='verification_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('pending_review', 'Pending review'), ('rejected', 'Rejected'), ('ordered', 'Ordered (not yet administered)'), ('declined', 'Declined / not required')], db_index=True, default='verified', max_length=20),
        ),
    ]
