# Generated by Django 4.2.13 on 2026-08-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_sharedvaccination_dose_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('password_reset_staff', 'Staff password reset'), ('password_reset_patient', 'Patient password reset'), ('registration_patient', 'Patient registration'), ('login_patient', 'Patient OTP login'), ('contact_change_patient', 'Patient mobile-number change')], db_index=True, max_length=30)),
                ('identifier', models.CharField(db_index=True, max_length=254)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('code_hash', models.CharField(max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=10)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_db', models.CharField(blank=True, max_length=100)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_code',
                'indexes': [models.Index(fields=['identifier', 'purpose', '-created_at'], name='otp_code_identif_c6fe4e_idx')],
            },
        ),
    ]
