# Generated by Django 4.2.13 on 2026-08-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0020_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30)),
                ('event', models.CharField(choices=[('generated', 'QR code generated'), ('viewed', 'Summary viewed')], max_length=10)),
                ('generated_by_account_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emergency_access_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
