# Generated by Django 4.2.13 on 2026-08-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_emergencyaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyaccesslog',
            name='consent_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
