# Generated by Django 4.2.13 on 2026-09-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0022_emergencyaccesslog_consent_confirmed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffEmailIndex',
        ),
    ]
