# Generated by Django 4.2.13 on 2026-09-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0023_consult_pad_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultPadSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30)),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('shared_document_id', models.IntegerField(blank=True, null=True)),
                ('page_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=10)),
                ('recognized', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recognized_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consult_pad_submission',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['awpid', 'tenant_id', 'consumed_at'], name='consult_pad_awpid_e4b369_idx')],
            },
        ),
    ]
