# Generated by Django 4.2.13 on 2026-09-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0024_consultpadsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultpadsubmission',
            name='source_pages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
