# Generated by Django 4.2.13 on 2026-09-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0025_consultpadsubmission_source_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30)),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('encounter_id', models.UUIDField(db_index=True)),
                ('doctor_user_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('signed', 'Signed'), ('expired', 'Expired')], db_index=True, default='open', max_length=10)),
                ('rx_pages', models.JSONField(blank=True, default=list)),
                ('rx_recognised', models.JSONField(blank=True, null=True)),
                ('note_pages', models.JSONField(blank=True, default=list)),
                ('note_recognised', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consult_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ConsultPadSubmission',
        ),
        migrations.AddIndex(
            model_name='consultsession',
            index=models.Index(fields=['encounter_id', 'status'], name='consult_ses_encount_bf0f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='consultsession',
            index=models.Index(fields=['awpid', 'tenant_id', 'status'], name='consult_ses_awpid_3a7615_idx'),
        ),
    ]
