# Generated by Django 4.2.13 on 2026-09-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0023_remove_staffemailindex'),
        ('registry', '0027_my_reports_pipeline'),
    ]

    operations = [
    ]
