# Generated by Django 4.2.13 on 2026-09-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0027_my_reports_pipeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordsShareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=32, unique=True)),
                ('code', models.CharField(db_index=True, max_length=8)),
                ('requester_label', models.CharField(blank=True, max_length=120)),
                ('awpid', models.CharField(blank=True, db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Waiting for patient'), ('approved', 'Approved'), ('denied', 'Denied by patient'), ('ended', 'Ended by patient'), ('expired', 'Expired')], db_index=True, default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('download_unlocked_ids', models.JSONField(blank=True, default=list)),
                ('pending_download_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'records_share_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['awpid', 'status'], name='records_sha_awpid_2d7c25_idx')],
            },
        ),
    ]
