# Generated by Django 4.2.13 on 2026-09-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0028_recordssharerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordssharerequest',
            name='code_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
