# Generated by Django 4.2.13 on 2026-09-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0030_recordssharerequest_laptop_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddocument',
            name='category_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='category_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='date_source',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='report_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
