# Generated by Django 4.2.13 on 2026-09-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0033_shareddocument_review_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordsPrivacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30, unique=True)),
                ('hide_all', models.BooleanField(default=False)),
                ('hidden_doc_ids', models.JSONField(blank=True, default=list)),
                ('hidden_categories', models.JSONField(blank=True, default=list)),
                ('hidden_kinds', models.JSONField(blank=True, default=list)),
                ('hidden_sections', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'records_privacy',
            },
        ),
        migrations.AddField(
            model_name='recordssharerequest',
            name='shown_private_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='emergencyaccesslog',
            name='event',
            field=models.CharField(choices=[('generated', 'QR code generated'), ('viewed', 'Summary viewed'), ('privacy', 'Shared-records privacy changed')], max_length=24),
        ),
    ]
