# Generated by Django 4.2.13 on 2026-09-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0034_records_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddocument',
            name='review_needs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
