# Generated by Django 4.2.13 on 2026-09-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0028_merge_20260909_1932'),
        ('registry', '0035_shareddocument_review_needs'),
    ]

    operations = [
    ]
