# Generated by Django 4.2.13 on 2026-09-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0038_lab_extract_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordssharerequest',
            name='share_all',
            field=models.BooleanField(default=False),
        ),
    ]
