# Generated by Django 4.2.13 on 2026-09-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0038_lab_extract_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedvital',
            name='head_circumference_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
