# Generated by Django 4.2.13 on 2026-09-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0039_sharedvital_head_circumference'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('owner_tenant_id', models.IntegerField(blank=True, null=True)),
                ('is_template', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'milestone_schedule',
            },
        ),
        migrations.CreateModel(
            name='MilestoneScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('gross_motor', 'Gross Motor'), ('fine_motor', 'Fine Motor'), ('language', 'Language / Communication'), ('cognitive', 'Cognitive'), ('social_emotional', 'Social / Emotional')], max_length=20)),
                ('milestone', models.CharField(max_length=200)),
                ('scheduled_label', models.CharField(max_length=50)),
                ('min_age_days', models.PositiveIntegerField()),
                ('max_age_days', models.PositiveIntegerField(blank=True, null=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='registry.milestoneschedule')),
            ],
            options={
                'db_table': 'milestone_schedule_rule',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SharedMilestoneRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30)),
                ('domain', models.CharField(choices=[('gross_motor', 'Gross Motor'), ('fine_motor', 'Fine Motor'), ('language', 'Language / Communication'), ('cognitive', 'Cognitive'), ('social_emotional', 'Social / Emotional')], max_length=20)),
                ('milestone', models.CharField(max_length=200)),
                ('scheduled_label', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('achieved', 'Achieved'), ('not_yet', 'Not Yet'), ('concern', 'Concern Flagged')], default='achieved', max_length=10)),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('assessed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by_name', models.CharField(blank=True, max_length=200)),
                ('source_tenant_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shared_milestone_record',
                'ordering': ['assessed_date'],
                'indexes': [models.Index(fields=['awpid', 'domain'], name='shared_mile_awpid_a1f3c2_idx')],
            },
        ),
    ]
