# Generated by Django 4.2.13 on 2026-09-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0041_seed_default_milestone_schedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sharedmilestonerecord',
            new_name='shared_mile_awpid_26f35e_idx',
            old_name='shared_mile_awpid_a1f3c2_idx',
        ),
    ]
