# Generated by Django 4.2.13 on 2026-09-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0039_recordssharerequest_share_all'),
        ('registry', '0042_rename_shared_mile_awpid_a1f3c2_idx_shared_mile_awpid_26f35e_idx'),
    ]

    operations = [
    ]
