# Generated by Django 4.2.13 on 2026-09-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0043_merge_20260918_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedBirthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30, unique=True)),
                ('gestational_age_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('delivery_mode', models.CharField(blank=True, max_length=12)),
                ('multiple_birth', models.CharField(blank=True, max_length=50)),
                ('nicu_admission', models.BooleanField(default=False)),
                ('nicu_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_complications', models.TextField(blank=True)),
                ('congenital_conditions', models.TextField(blank=True)),
                ('apgar_score_1min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('apgar_score_5min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_tenant_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shared_birth_history',
            },
        ),
    ]
