# Generated by Django 4.2.13 on 2026-09-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0044_sharedbirthhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaccount',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
