# Generated by Django 4.2.13 on 2026-09-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0044_sharedbirthhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentuploaditem',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='documentuploaditem',
            name='result_document',
        ),
        migrations.RemoveField(
            model_name='extractedlabvalue',
            name='document',
        ),
        migrations.RemoveField(
            model_name='shareddocument',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='shareddocument',
            name='is_duplicate_of',
        ),
        migrations.DeleteModel(
            name='DocumentUploadBatch',
        ),
        migrations.DeleteModel(
            name='DocumentUploadItem',
        ),
        migrations.DeleteModel(
            name='ExtractedLabValue',
        ),
        migrations.DeleteModel(
            name='SharedDocument',
        ),
    ]
