# Generated by Django 4.2.13 on 2026-09-24 05:31

from django.db import migrations, models


# Seed values for the keyword-rules table: the vocabulary that used to live
# only in core/doc_classifier.py. Imported (not copied) because those tuples
# stay in the code as the fallback used when the table is empty.
_SEED = [
    # doc_type, name, tuple attr, required_hits
    ("lab_report",        "Lab report — core",        "_LAB_HINTS",         5),
    ("prescription",      "Prescription — core",      "_RX_HINTS",          5),
    ("scan",              "Imaging — core",           "_IMG_HINTS",         3),
    ("discharge_summary", "Discharge summary — core", "_DISCHARGE_HINTS",   3),
    ("not_medical",       "Not medical — core",       "_NON_MEDICAL_HINTS", 2),
]


def seed_rules(apps, schema_editor):
    from core import doc_classifier as dc
    Rule = apps.get_model("registry", "DocumentClassificationRule")
    if Rule.objects.using(schema_editor.connection.alias).exists():
        return
    for doc_type, name, attr, req in _SEED:
        words = [w.strip() for w in getattr(dc, attr) if w.strip()]
        Rule.objects.using(schema_editor.connection.alias).create(
            doc_type=doc_type, name=name, keywords="|".join(words),
            required_hits=req, is_active=True, updated_by="migration",
        )


def backfill_status(apps, schema_editor):
    """Rows that predate the pipeline are already processed. Their label is
    'closed' when a person or the hospital QR set it, else 'partial'."""
    Doc = apps.get_model("registry", "SharedDocument")
    qs = Doc.objects.using(schema_editor.connection.alias)
    qs.update(processing_status="done", classification_status="partial")
    qs.filter(
        models.Q(verification_status="verified")
        | models.Q(uploaded_by="staff")
        | models.Q(classification_method__in=("qr", "staff", "patient_confirmed"))
    ).update(classification_status="closed")


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0045_patientaccount_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('prescription', 'Prescription'), ('lab_report', 'Lab Report'), ('scan', 'Scan / Imaging'), ('discharge_summary', 'Discharge Summary'), ('not_medical', 'Not medical (negative)')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('keywords', models.TextField()),
                ('required_hits', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'doc_classification_rule',
                'ordering': ['doc_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='classification_status',
            field=models.CharField(db_index=True, default='closed', max_length=10),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='human_action',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='human_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='human_doc_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='llm_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='llm_doc_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='llm_model',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='llm_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='processing_error',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='processing_status',
            field=models.CharField(db_index=True, default='done', max_length=12),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='rule_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='rule_doc_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='rule_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(seed_rules, migrations.RunPython.noop),
        migrations.RunPython(backfill_status, migrations.RunPython.noop),
    ]
