# Generated by Django 4.2.13 on 2026-09-24 05:57

import json

from django.db import migrations, models


# Starter jobs for platform admin → Background Jobs. Only the one that works
# out of the box is enabled; the rest are there to switch on from the screen.
# (Beat adds its own daily `celery.backend_cleanup` job for task history.)
_JOBS = [
    # name, task, schedule, kwargs, enabled, description
    ("Retry stuck document uploads", "core.process_pending_documents",
     ("interval", 5, "minutes"), {"stale": 300, "retry_failed": False}, True,
     "Runs any My Reports upload still queued after 5 minutes (its worker died or none was running)."),
    ("Extract lab values", "core.extract_lab_values",
     ("interval", 15, "minutes"), {"limit": 50}, False,
     "Reads test values out of filed lab reports (needs LAB_EXTRACTOR LLM configured)."),
    ("Drain folder uploads", "core.process_document_batches",
     ("interval", 1, "minutes"), {"limit": 0}, False,
     "Files documents uploaded through the direct-to-S3 folder/batch upload flow."),
    ("Daily reminders — all hospitals", "core.generate_reminders",
     ("crontab", "0", "7", "*", "*", "*"), {}, False,
     "Appointment and follow-up reminders for every active hospital."),
]


def seed(apps, schema_editor):
    alias = schema_editor.connection.alias
    Config = apps.get_model("registry", "CeleryRuntimeConfig")
    Config.objects.using(alias).get_or_create(pk=1)

    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    Interval = apps.get_model("django_celery_beat", "IntervalSchedule")
    Crontab = apps.get_model("django_celery_beat", "CrontabSchedule")
    for name, task, sched, kwargs, enabled, desc in _JOBS:
        if PeriodicTask.objects.using(alias).filter(name=name).exists():
            continue
        fields = {}
        if sched[0] == "interval":
            fields["interval"], _ = Interval.objects.using(alias).get_or_create(every=sched[1], period=sched[2])
        else:
            m, h, dow, dom, moy = sched[1:]
            fields["crontab"], _ = Crontab.objects.using(alias).get_or_create(
                minute=m, hour=h, day_of_week=dow, day_of_month=dom, month_of_year=moy,
                timezone="Asia/Kolkata")
        PeriodicTask.objects.using(alias).create(
            name=name, task=task, kwargs=json.dumps(kwargs), args="[]",
            enabled=enabled, description=desc, **fields)


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0046_doc_async_classification'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryRuntimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_url', models.CharField(blank=True, max_length=300)),
                ('worker_pool', models.CharField(default='solo', max_length=10)),
                ('worker_concurrency', models.PositiveSmallIntegerField(default=2)),
                ('worker_queues', models.CharField(default='celery', max_length=200)),
                ('worker_loglevel', models.CharField(default='INFO', max_length=10)),
                ('inline_fallback', models.BooleanField(default=True)),
                ('worker_pid', models.IntegerField(blank=True, null=True)),
                ('worker_started_at', models.DateTimeField(blank=True, null=True)),
                ('worker_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('worker_hostname', models.CharField(blank=True, max_length=120)),
                ('beat_pid', models.IntegerField(blank=True, null=True)),
                ('beat_started_at', models.DateTimeField(blank=True, null=True)),
                ('beat_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'celery_runtime_config',
            },
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
