# Generated by Django 4.2.13 on 2026-09-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0047_celery_runtime_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddocument',
            name='folder',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
