# Generated by Django 4.2.13 on 2026-09-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0048_shareddocument_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeryruntimeconfig',
            name='flower_pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='celeryruntimeconfig',
            name='flower_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
