# Generated by Django 4.2.13 on 2026-09-25 04:35

from django.db import migrations, models


def forwards(apps, schema_editor):
    alias = schema_editor.connection.alias
    Doc = apps.get_model("registry", "SharedDocument")
    # Documents the LLM already looked at (inline, before the queue existed).
    Doc.objects.using(alias).exclude(llm_doc_type="").update(llm_status="done")

    # The existing worker also consumes the new "llm" queue.
    Config = apps.get_model("registry", "CeleryRuntimeConfig")
    Config.objects.using(alias).filter(worker_queues="celery").update(worker_queues="celery,llm")

    # Beat nudges the LLM queue every minute, so it resumes on its own once
    # the LLM server is reachable again.
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    Interval = apps.get_model("django_celery_beat", "IntervalSchedule")
    if not PeriodicTask.objects.using(alias).filter(name="Run the AI queue").exists():
        every_min, _ = Interval.objects.using(alias).get_or_create(every=1, period="minutes")
        PeriodicTask.objects.using(alias).create(
            name="Run the AI queue", task="core.llm_drain", interval=every_min,
            kwargs="{}", args="[]", queue="llm", enabled=True,
            description="Sends queued documents to the LLM one at a time; waits while the LLM server is down.",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0049_celery_runtime_flower'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddocument',
            name='llm_queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='llm_status',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='celeryruntimeconfig',
            name='worker_queues',
            field=models.CharField(default='celery,llm', max_length=200),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
