# Generated by Django 4.2.13 on 2026-09-25 04:54

from django.db import migrations, models


def seed(apps, schema_editor):
    """The periodic job that works through big uploads, a batch per run."""
    alias = schema_editor.connection.alias
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    Interval = apps.get_model("django_celery_beat", "IntervalSchedule")
    if not PeriodicTask.objects.using(alias).filter(name="Process bulk uploads").exists():
        every2, _ = Interval.objects.using(alias).get_or_create(every=2, period="minutes")
        PeriodicTask.objects.using(alias).create(
            name="Process bulk uploads", task="core.process_bulk_documents", interval=every2,
            kwargs="{}", args="[]", enabled=True,
            description="Sorts uploads bigger than the instant threshold, a batch per run (oldest first).",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0050_llm_queue'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeryruntimeconfig',
            name='bulk_batch_limit',
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='celeryruntimeconfig',
            name='instant_max_files',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='shareddocument',
            name='processing_route',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
