# Generated by Django 4.2.13 on 2026-09-25 05:27

from django.db import migrations, models


def one_worker(apps, schema_editor):
    """Start simple: 1 worker (one file at a time) — raise it on Background Jobs → Settings."""
    Config = apps.get_model("registry", "CeleryRuntimeConfig")
    Config.objects.using(schema_editor.connection.alias).update(worker_concurrency=1)


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0052_rules_bill_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celeryruntimeconfig',
            name='worker_concurrency',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(one_worker, migrations.RunPython.noop),
    ]
