# Generated by Django 4.2.13 on 2026-09-23 15:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0053_one_worker_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awpid', models.CharField(db_index=True, max_length=30)),
                ('total_files', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('partial', 'Partial')], db_index=True, default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'extraction_batch',
            },
        ),
        migrations.CreateModel(
            name='ExtractionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awpid', models.CharField(db_index=True, max_length=30)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('declared_size', models.IntegerField(default=0)),
                ('staging_key', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='uploading', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('extracted_text', models.TextField(blank=True)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
                ('page_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='registry.extractionbatch')),
            ],
            options={
                'db_table': 'extraction_item',
            },
        ),
        migrations.AddIndex(
            model_name='extractionbatch',
            index=models.Index(fields=['awpid', 'status'], name='extract_batch_awpid_status_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionitem',
            index=models.Index(fields=['batch', 'status'], name='extract_item_batch_status_idx'),
        ),
    ]
