# Generated by Django 4.2.13 on 2026-09-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0054_extractionbatch_extractionitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionbatch',
            name='initiated_by_awpid',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='PushDeviceToken',
            fields=[
                ('token', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('awpid', models.CharField(db_index=True, max_length=30)),
                ('platform', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'push_device_token',
                'indexes': [models.Index(fields=['awpid'], name='push_token_awpid_idx')],
            },
        ),
    ]
