# Generated by Django 4.2.13 on 2026-09-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0061_seed_extraction_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionitem',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_items', to='registry.shareddocument'),
        ),
    ]
