"""
apps/notifications/models.py
-----------------------------
Tables: NotificationLog

feat_whatsapp gate enforced at API view level for WhatsApp channel.

NotificationTemplate and DeviceToken were retired in the v7 table-count
redesign — verified against the real codebase first: zero call sites for
either, anywhere outside this file (no urls.py mount for this app at all,
and grep across the repo turns up nothing but their own class definitions).
NotificationLog is NOT dead scaffolding, despite living in the same app —
it's written by generate_reminders (see services.py) and read/written by
apps.patients.portal_views.PortalNotificationsView /
PortalNotificationMarkReadView, a real endpoint mounted at
/api/v1/portal/notifications/. Kept as-is, minus the `template` FK (which
only ever pointed at the now-removed NotificationTemplate and was never
actually set by any real write path).
"""

from django.db import models
from apps.patients.models import Patient


class NotificationLog(models.Model):
    """
    Delivery log for every notification attempt.
    Keeps an audit trail regardless of success/failure.
    """
    STATUS_CHOICES = [
        ("queued",    "Queued"),
        ("sent",      "Sent"),
        ("delivered", "Delivered"),
        ("failed",    "Failed"),
    ]

    patient     = models.ForeignKey(Patient, on_delete=models.SET_NULL,
                                    null=True, blank=True, related_name="notifications")
    recipient   = models.CharField(max_length=200)  # phone or email
    channel     = models.CharField(max_length=20)
    body        = models.TextField()                 # rendered body (after variable substitution)
    status      = models.CharField(max_length=20, choices=STATUS_CHOICES, default="queued", db_index=True)
    provider_ref= models.CharField(max_length=200, blank=True)  # external message ID
    error       = models.TextField(blank=True)
    sent_at     = models.DateTimeField(null=True, blank=True)
    created_at  = models.DateTimeField(auto_now_add=True)

    # Idempotency key for generated reminders (e.g. "appt_reminder:<uuid>",
    # "followup:<uuid>") so a daily cron re-run doesn't re-notify the same
    # patient for the same event — see apps/notifications/services.py. Blank
    # for anything not generated by the reminder job (e.g. a future
    # invoice_issued/report_ready notification fired from a request handler,
    # which is inherently a one-shot event with nothing to de-duplicate against).
    reference   = models.CharField(max_length=100, blank=True, db_index=True)
    # When the patient viewed this in their in-app notification list. Only
    # meaningful for channel="in_app" — SMS/email/push have their own
    # provider-side delivery concept (sent_at) that isn't "read".
    read_at     = models.DateTimeField(null=True, blank=True)

    class Meta:
        app_label = "notifications"
        db_table  = "notification_log"
        ordering  = ["-created_at"]
