# Generated by Django 4.2.13 on 2026-07-30 09:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('patient_awpid', models.CharField(db_index=True, max_length=22)),
                ('doctor_user_id', models.UUIDField(db_index=True)),
                ('doctor_name', models.CharField(max_length=255)),
                ('appointment_type', models.CharField(choices=[('opd', 'OPD'), ('followup', 'Follow-up'), ('emergency', 'Emergency')], default='opd', max_length=15)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=15)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('token_number', models.IntegerField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('booked_by_user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appointment',
                'ordering': ['scheduled_date', 'token_number'],
            },
        ),
        migrations.CreateModel(
            name='OPDEncounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('doctor_user_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed')], default='draft', max_length=10)),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('diagnoses', models.JSONField(blank=True, default=list)),
                ('referred_to', models.CharField(blank=True, max_length=255)),
                ('referral_notes', models.TextField(blank=True)),
                ('ai_transcript_job_id', models.CharField(blank=True, max_length=100)),
                ('ai_transcript_text', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encounter', to='opd.appointment')),
            ],
            options={
                'db_table': 'opd_encounter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('doctor_user_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dispensed', 'Dispensed'), ('expired', 'Expired')], default='active', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='opd.opdencounter')),
            ],
            options={
                'db_table': 'opd_prescription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by_user_id', models.UUIDField(blank=True, null=True)),
                ('systolic_bp', models.IntegerField(blank=True, null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('spo2', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='opd.appointment')),
            ],
            options={
                'db_table': 'vitals',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('od', 'Once Daily'), ('bd', 'Twice Daily'), ('td', 'Three Times Daily'), ('qid', 'Four Times Daily'), ('sos', 'As Needed'), ('stat', 'Immediately'), ('nocte', 'At Night'), ('mane', 'In the Morning')], max_length=10)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous'), ('im', 'Intramuscular'), ('sc', 'Subcutaneous'), ('topical', 'Topical'), ('inhaled', 'Inhaled'), ('rectal', 'Rectal'), ('sublingual', 'Sublingual')], default='oral', max_length=15)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('is_controlled', models.BooleanField(default=False)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='opd.prescription')),
            ],
            options={
                'db_table': 'opd_prescription_item',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionFavourite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_user_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prescription_favourite',
                'unique_together': {('doctor_user_id', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_date', 'doctor_user_id'], name='appointment_schedul_446ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient_id', 'scheduled_date'], name='appointment_patient_d94625_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'scheduled_date'], name='appointment_status_d9cda3_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient_id'], name='opd_prescri_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='opdencounter',
            index=models.Index(fields=['patient_id'], name='opd_encount_patient_fa14c2_idx'),
        ),
        migrations.AddIndex(
            model_name='opdencounter',
            index=models.Index(fields=['doctor_user_id', 'status'], name='opd_encount_doctor__769594_idx'),
        ),
    ]
