# Generated by Django 4.2.13 on 2026-08-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_encounter_extras'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='prescription',
            new_name='opd_prescri_patient_7eb5c3_idx',
            old_name='opd_prescri_patient_idx',
        ),
        migrations.AddField(
            model_name='appointment',
            name='branch_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_awpid',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting'), ('vitals_done', 'Vitals Done'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=15),
        ),
    ]
