# Generated by Django 4.2.13 on 2026-08-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0004_rename_opd_prescri_patient_idx_opd_prescri_patient_7eb5c3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_preference',
            field=models.CharField(choices=[('pay_at_desk', 'Pay at Front Desk'), ('pay_online', 'Pay Online')], default='pay_at_desk', max_length=15),
        ),
    ]
