# Generated by Django 4.2.13 on 2026-08-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0005_appointment_payment_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting'), ('vitals_done', 'Vitals Done'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=15),
        ),
        migrations.AlterField(
            model_name='opdencounter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dispensed', 'Dispensed'), ('expired', 'Expired')], db_index=True, default='active', max_length=15),
        ),
    ]
