# Generated by Django 4.2.13 on 2026-08-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_alter_prescription_status'),
        ('opd', '0006_alter_appointment_status_alter_opdencounter_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='prescriptions.drug'),
        ),
    ]
