# Generated by Django 4.2.13 on 2026-08-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0007_prescriptionitem_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='floor',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='room_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
