# Generated by Django 4.2.13 on 2026-08-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_invoice_encounter'),
        ('opd', '0008_appointment_floor_appointment_room_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='choice_made_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='choice_made_by',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('nurse', 'Nurse')], max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_choice',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_house', 'In-House'), ('outside', 'Outside')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='payment_preference',
            field=models.CharField(blank=True, choices=[('pay_online', 'Pay Online'), ('pay_at_pharmacy', 'Pay at Pharmacy')], max_length=15),
        ),
        migrations.AddField(
            model_name='prescription',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending_online', 'Pending Online Payment'), ('paid', 'Paid')], default='unpaid', max_length=15),
        ),
        migrations.AddField(
            model_name='prescription',
            name='rx_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['rx_number'], name='opd_prescri_rx_numb_474241_idx'),
        ),
    ]
