# Generated by hand — NOT run against a live database in this session (see
# apps/ipd/migrations/0001_initial.py for the same caveat). Run
# `python manage.py migrate` and `python manage.py migrate_tenants` before
# relying on this.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opd", "0009_prescription_choice_made_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opdencounter",
            name="followup_ask_nurse",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opdencounter",
            name="followup_nurse_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="opdencounter",
            name="followup_nurse_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opdencounter",
            name="followup_nurse_booked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opdencounter",
            name="followup_nurse_booked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
