# Generated by Django 4.2.13 on 2026-09-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0010_followup_nurse_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(default='opd', max_length=15),
        ),
    ]
