# Generated by Django 4.2.13 on 2026-09-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0012_seed_appointment_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='head_circumference_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
