# Generated by Django 4.2.13 on 2026-08-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('dispensed', 'Dispensed')], db_index=True, default='draft', max_length=20),
        ),
    ]
