# Generated by Django 4.2.13 on 2026-08-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_configurable_drug_forms'),
        # pharmacy.Dispense.prescription_item and
        # pharmacy.MedicationDoseLog.prescription_item originally pointed at
        # prescriptions.prescriptionitem; pharmacy/0003 repoints both to
        # opd.prescriptionitem. Without this dependency, the planner could
        # delete PrescriptionItem (below) before pharmacy has repointed
        # away from it, leaving a dangling FK reference that fails with
        # "Related model 'prescriptions.prescriptionitem' cannot be
        # resolved" when the schema editor generates SQL for pharmacy's
        # tables — same class of bug as clinical/0003's dependency on
        # lab/0003 above.
        ('pharmacy', '0003_alter_dispense_prescription_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='prescription',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='PrescriptionItem',
        ),
    ]
