# Generated by Django 4.2.13 on 2026-08-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_remove_prescriptionitem_drug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='default_mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
