# Generated by Django 4.2.13 on 2026-09-26 05:01

from django.db import migrations, models

# Starting rules (what used to be hardcoded). From here on they're edited in
# Platform Admin → Classification rules.
STARTING_RULES = {
    "prescription": "prescription|tablet|medicine|dosage|rx",
    "lab_report": "laboratory|hemoglobin|glucose|cholesterol|reference range",
    "scan": "x-ray|mri|ct scan|ultrasound|radiology",
    "discharge_summary": "discharge|admitted|hospital course|diagnosis",
}


def add_starting_rules(apps, schema_editor):
    Rule = apps.get_model("records", "ClassificationRule")
    for doc_type, keywords in STARTING_RULES.items():
        Rule.objects.using(schema_editor.connection.alias).get_or_create(doc_type=doc_type, defaults={"keywords": keywords})
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # the old registry shared_document table must be gone first (same table name)
        ("registry", "0045_drop_old_document_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=30, unique=True)),
                ('keywords', models.TextField(help_text='Pipe-separated, e.g. laboratory|hemoglobin|glucose|reference range')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'classification_rule',
                'ordering': ['doc_type'],
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'upload_batch',
            },
        ),
        migrations.CreateModel(
            name='SharedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awpid', models.CharField(db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(default='other', max_length=30)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('s3_key', models.CharField(max_length=500)),
                ('uploaded_by', models.CharField(default='patient', max_length=10)),
                ('source_tenant_id', models.IntegerField(blank=True, null=True)),
                ('source_ref', models.CharField(blank=True, db_index=True, max_length=120)),
                ('public_document_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('hospital_label', models.CharField(blank=True, max_length=120)),
                ('doctor_label', models.CharField(blank=True, max_length=120)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('processing_status', models.CharField(db_index=True, default='completed', max_length=12)),
                ('extracted_text', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('error', models.TextField(blank=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='records.uploadbatch')),
            ],
            options={
                'db_table': 'shared_document',
                'indexes': [models.Index(fields=['awpid', 'doc_type'], name='shared_doc_awpid_type_idx')],
            },
        ),
        migrations.RunPython(add_starting_rules, migrations.RunPython.noop),
    ]
