# Generated by Django 4.2.13 on 2026-09-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SweepConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant_max_files', models.PositiveIntegerField(default=5)),
                ('sweep_dispatch_limit', models.PositiveIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'records_sweep_config',
            },
        ),
    ]
