# Generated by Django 4.2.13 on 2026-09-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_sweepconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweepconfig',
            name='sweep_interval_seconds',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
