"""
apps/patients/models.py
-----------------------
Per-tenant patient record. Links to the global PatientIdentity via awpid.

Patient — tenant-local record with UHID, registration date, etc.
Allergy — tenant-local allergy records (also written to shared_allergy on create)
"""

import uuid as _uuid
from django.db import models
from apps.org.models import Branch


class Patient(models.Model):
    """
    Per-hospital patient record.
    awpid links to registry.PatientIdentity (different DB — no FK constraint).
    UHID is hospital-local (generated by NNTM).
    """
    GENDER_CHOICES = [("M", "Male"), ("F", "Female"), ("O", "Other")]
    PAYER_CHOICES  = [("self", "Self Pay"), ("insurance", "Insurance"), ("corporate", "Corporate")]

    uuid            = models.UUIDField(default=_uuid.uuid4, unique=True, db_index=True)
    awpid           = models.CharField(max_length=30, db_index=True)
    uhid            = models.CharField(max_length=20, unique=True)  # e.g. APL-000123
    branch          = models.ForeignKey(Branch, on_delete=models.PROTECT,
                                        related_name="patients")
    # Personal
    full_name       = models.CharField(max_length=200)
    date_of_birth   = models.DateField(null=True, blank=True)
    gender          = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    blood_group     = models.CharField(max_length=5, blank=True)
    marital_status  = models.CharField(max_length=20, blank=True)
    nationality     = models.CharField(max_length=50, blank=True, default="Indian")
    occupation      = models.CharField(max_length=100, blank=True)

    # Contact
    mobile          = models.CharField(max_length=15, blank=True)  # plain per-tenant (DPDP: no plain mobile in Registry)
    alternate_mobile= models.CharField(max_length=15, blank=True)
    email           = models.EmailField(blank=True)
    address_line1   = models.CharField(max_length=255, blank=True)
    city            = models.CharField(max_length=100, blank=True)
    state           = models.CharField(max_length=100, blank=True)
    pincode         = models.CharField(max_length=10, blank=True)

    # Dependent patients (children, or anyone with no mobile of their own) —
    # plain per-tenant copy of the guardian's details, for display at this
    # hospital only. The actual cross-hospital identity link lives in
    # registry.PatientRelationship, keyed by AWPID, not these fields.
    is_dependent        = models.BooleanField(default=False)
    guardian_name        = models.CharField(max_length=200, blank=True)
    guardian_mobile       = models.CharField(max_length=15, blank=True)
    guardian_relation     = models.CharField(max_length=20, blank=True)  # child/parent/spouse/sibling/ward/other
    guardian_awpid        = models.CharField(max_length=30, blank=True)  # the guardian's own AWPID, for reference

    # Emergency contact
    emergency_contact_name     = models.CharField(max_length=100, blank=True)
    emergency_contact_phone    = models.CharField(max_length=15, blank=True)
    emergency_contact_relation = models.CharField(max_length=50, blank=True)

    # Insurance / payment
    payer_type         = models.CharField(max_length=20, choices=PAYER_CHOICES, default="self")
    insurance_provider = models.CharField(max_length=200, blank=True)
    policy_number      = models.CharField(max_length=100, blank=True)
    tpa_name           = models.CharField(max_length=200, blank=True)

    # DPDP consent (Digital Personal Data Protection Act 2023) — consent to
    # this hospital processing the patient's data at all.
    dpdp_consent_captured = models.BooleanField(default=False)
    dpdp_consent_at       = models.DateTimeField(null=True, blank=True)

    # HIE consent — separate from the above: specifically, the patient
    # agreeing that THIS hospital may pull in their shared cross-hospital
    # history (diagnoses, allergies, vitals, prescriptions, lab results,
    # documents) via the Registry DB. Asked once, the first time a patient
    # books/registers at a new hospital through the patient portal — see
    # PortalBookView. Defaults False; front-desk walk-in registration
    # doesn't currently set this (out of scope here — that flow can be
    # updated separately if paper/verbal consent should be captured too).
    hie_consent_given = models.BooleanField(default=False)
    hie_consent_at    = models.DateTimeField(null=True, blank=True)

    preferred_language = models.CharField(max_length=10, default="en")
    registered_at   = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

    # ── Emergency / unidentified patient intake ──────────────────────────
    # See docs/PENDING_IMPROVEMENTS.md item 1. A patient registered with no
    # ID and no family present starts "provisional" — enough to open a
    # chart and treat, not a claim that this is a confirmed identity.
    # identity_status stays "confirmed" (the default) for every normal
    # registration; nothing about existing rows or the normal register()
    # path changes.
    IDENTITY_CONFIRMED   = "confirmed"
    IDENTITY_PROVISIONAL = "provisional"
    IDENTITY_STATUS_CHOICES = [
        (IDENTITY_CONFIRMED, "Confirmed"),
        (IDENTITY_PROVISIONAL, "Provisional"),
    ]
    ARRIVAL_AMBULANCE   = "ambulance"
    ARRIVAL_BROUGHT_IN  = "brought_in"
    ARRIVAL_POLICE_CASE = "police_case"
    ARRIVAL_WALK_IN_UNRESPONSIVE = "walk_in_unresponsive"
    ARRIVAL_OTHER       = "other"
    ARRIVAL_CHANNEL_CHOICES = [
        (ARRIVAL_AMBULANCE, "Ambulance"),
        (ARRIVAL_BROUGHT_IN, "Brought in"),
        (ARRIVAL_POLICE_CASE, "Police case"),
        (ARRIVAL_WALK_IN_UNRESPONSIVE, "Walk-in, unresponsive"),
        (ARRIVAL_OTHER, "Other"),
    ]

    identity_status = models.CharField(max_length=12, choices=IDENTITY_STATUS_CHOICES, default=IDENTITY_CONFIRMED)
    # Mirrors ipd.AdmissionReferral.is_mlc, but at the patient level — an
    # MLC (Medico-Legal Case) flag needs to travel with the patient from
    # the moment of registration, before any admission referral exists at
    # all (e.g. an emergency OPD-only encounter that never becomes an
    # admission is still an MLC case).
    is_mlc          = models.BooleanField(default=False)
    arrival_channel = models.CharField(max_length=25, choices=ARRIVAL_CHANNEL_CHOICES, blank=True)
    # e.g. "Unknown Male, approx. 30yrs" — shown instead of full_name until
    # the identity is confirmed (see #2 in the same backlog item, "identity
    # merge", not built yet — this field just makes the label explicit
    # rather than overloading full_name with a placeholder value).
    placeholder_label = models.CharField(max_length=200, blank=True)
    # Auto-logged reason when DPDP/HIE consent is skipped under the
    # emergency-treatment doctrine (see ipd.AdmissionDeposit's docstring for
    # the same legal basis, cited there re: advance-payment gating) — never
    # left implicit as "consent just wasn't captured".
    consent_deferred_reason = models.CharField(max_length=255, blank=True)

    class Meta:
        app_label = "patients"
        db_table  = "patient"

    def __str__(self):
        return f"{self.uhid} — {self.full_name}"


class Allergy(models.Model):
    """
    Patient allergy record. On create/update a Django signal writes a
    sanitized copy to registry.SharedAllergy for cross-tenant visibility.
    """
    SEVERITY_CHOICES = [
        ("mild",     "Mild"),
        ("moderate", "Moderate"),
        ("severe",   "Severe"),
    ]

    patient     = models.ForeignKey(Patient, on_delete=models.CASCADE,
                                    related_name="allergies")
    substance   = models.CharField(max_length=200)
    reaction    = models.TextField(blank=True)
    severity    = models.CharField(max_length=20, choices=SEVERITY_CHOICES, blank=True)
    is_active   = models.BooleanField(default=True)
    recorded_at = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)
    recorded_by = models.IntegerField(null=True, blank=True)  # StaffUser.id

    class Meta:
        app_label = "patients"
        db_table  = "allergy"

    def __str__(self):
        return f"{self.patient.uhid} — {self.substance}"
