"""
apps/patients/models.py
-----------------------
Per-tenant patient record. Links to the global PatientIdentity via awpid.

Patient — tenant-local record with UHID, registration date, etc.
Allergy — tenant-local allergy records (also written to shared_allergy on create)
"""

import uuid as _uuid
from django.db import models
from apps.org.models import Branch


class Patient(models.Model):
    """
    Per-hospital patient record.
    awpid links to registry.PatientIdentity (different DB — no FK constraint).
    UHID is hospital-local (generated by NNTM).
    """
    GENDER_CHOICES = [("M", "Male"), ("F", "Female"), ("O", "Other")]
    PAYER_CHOICES  = [("self", "Self Pay"), ("insurance", "Insurance"), ("corporate", "Corporate")]

    uuid            = models.UUIDField(default=_uuid.uuid4, unique=True, db_index=True)
    awpid           = models.CharField(max_length=30, db_index=True)
    uhid            = models.CharField(max_length=20, unique=True)  # e.g. APL-000123
    branch          = models.ForeignKey(Branch, on_delete=models.PROTECT,
                                        related_name="patients")
    # Personal
    full_name       = models.CharField(max_length=200)
    date_of_birth   = models.DateField(null=True, blank=True)
    gender          = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    blood_group     = models.CharField(max_length=5, blank=True)
    marital_status  = models.CharField(max_length=20, blank=True)
    nationality     = models.CharField(max_length=50, blank=True, default="Indian")
    occupation      = models.CharField(max_length=100, blank=True)

    # Contact
    mobile          = models.CharField(max_length=15, blank=True)  # plain per-tenant (DPDP: no plain mobile in Registry)
    alternate_mobile= models.CharField(max_length=15, blank=True)
    email           = models.EmailField(blank=True)
    address_line1   = models.CharField(max_length=255, blank=True)
    city            = models.CharField(max_length=100, blank=True)
    state           = models.CharField(max_length=100, blank=True)
    pincode         = models.CharField(max_length=10, blank=True)

    # Dependent patients (children, or anyone with no mobile of their own) —
    # plain per-tenant copy of the guardian's details, for display at this
    # hospital only. The actual cross-hospital identity link lives in
    # registry.PatientRelationship, keyed by AWPID, not these fields.
    is_dependent        = models.BooleanField(default=False)
    guardian_name        = models.CharField(max_length=200, blank=True)
    guardian_mobile       = models.CharField(max_length=15, blank=True)
    guardian_relation     = models.CharField(max_length=20, blank=True)  # child/parent/spouse/sibling/ward/other
    guardian_awpid        = models.CharField(max_length=30, blank=True)  # the guardian's own AWPID, for reference

    # Emergency contact
    emergency_contact_name     = models.CharField(max_length=100, blank=True)
    emergency_contact_phone    = models.CharField(max_length=15, blank=True)
    emergency_contact_relation = models.CharField(max_length=50, blank=True)

    # Insurance / payment
    payer_type         = models.CharField(max_length=20, choices=PAYER_CHOICES, default="self")
    insurance_provider = models.CharField(max_length=200, blank=True)
    policy_number      = models.CharField(max_length=100, blank=True)
    tpa_name           = models.CharField(max_length=200, blank=True)

    # DPDP consent (Digital Personal Data Protection Act 2023) — consent to
    # this hospital processing the patient's data at all.
    dpdp_consent_captured = models.BooleanField(default=False)
    dpdp_consent_at       = models.DateTimeField(null=True, blank=True)

    # HIE consent — separate from the above: specifically, the patient
    # agreeing that THIS hospital may pull in their shared cross-hospital
    # history (diagnoses, allergies, vitals, prescriptions, lab results,
    # documents) via the Registry DB. Asked once, the first time a patient
    # books/registers at a new hospital through the patient portal — see
    # PortalBookView. Defaults False; front-desk walk-in registration
    # doesn't currently set this (out of scope here — that flow can be
    # updated separately if paper/verbal consent should be captured too).
    hie_consent_given = models.BooleanField(default=False)
    hie_consent_at    = models.DateTimeField(null=True, blank=True)

    preferred_language = models.CharField(max_length=10, default="en")
    registered_at   = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

    class Meta:
        app_label = "patients"
        db_table  = "patient"

    def __str__(self):
        return f"{self.uhid} — {self.full_name}"


class Allergy(models.Model):
    """
    Patient allergy record. On create/update a Django signal writes a
    sanitized copy to registry.SharedAllergy for cross-tenant visibility.
    """
    SEVERITY_CHOICES = [
        ("mild",     "Mild"),
        ("moderate", "Moderate"),
        ("severe",   "Severe"),
    ]

    patient     = models.ForeignKey(Patient, on_delete=models.CASCADE,
                                    related_name="allergies")
    substance   = models.CharField(max_length=200)
    reaction    = models.TextField(blank=True)
    severity    = models.CharField(max_length=20, choices=SEVERITY_CHOICES, blank=True)
    is_active   = models.BooleanField(default=True)
    recorded_at = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)
    recorded_by = models.IntegerField(null=True, blank=True)  # StaffUser.id

    class Meta:
        app_label = "patients"
        db_table  = "allergy"

    def __str__(self):
        return f"{self.patient.uhid} — {self.substance}"
