"""
apps/billing/models.py
----------------------
Tables: BillingService (catalog), Invoice, InvoiceItem, Payment
invoice_number generated by NNTM (entity="INV").
"""

from django.db import models
from apps.org.models import StaffUser, Branch
from apps.patients.models import Patient
from apps.clinical.models import Encounter


class BillingService(models.Model):
    """Tenant-configured price list for services, procedures, etc."""
    CATEGORY_CHOICES = [
        ("consultation", "Consultation"),
        ("procedure",    "Procedure"),
        ("lab",          "Lab"),
        ("pharmacy",     "Pharmacy"),
        ("room",         "Room / Bed"),
        ("other",        "Other"),
    ]

    name        = models.CharField(max_length=200)
    code        = models.CharField(max_length=50, blank=True)
    category    = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default="other")
    unit_price  = models.DecimalField(max_digits=10, decimal_places=2)
    tax_rate    = models.DecimalField(max_digits=5, decimal_places=2, default=0)  # %
    is_active   = models.BooleanField(default=True)
    created_at  = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "billing"
        db_table  = "billing_service"
        ordering  = ["name"]

    def __str__(self):
        return f"{self.name} (₹{self.unit_price})"


class Invoice(models.Model):
    STATUS_CHOICES = [
        ("draft",          "Draft"),
        ("issued",         "Issued"),
        ("paid",           "Paid"),
        ("partially_paid", "Partially Paid"),
        ("cancelled",      "Cancelled"),
    ]

    PAYMENT_MODE_CHOICES = [
        ("cash",   "Cash"),
        ("card",   "Card"),
        ("upi",    "UPI"),
        ("online", "Online"),
        ("credit", "Credit"),
    ]

    patient         = models.ForeignKey(Patient, on_delete=models.PROTECT,
                                        related_name="invoices")
    encounter       = models.ForeignKey(Encounter, on_delete=models.SET_NULL,
                                        null=True, blank=True, related_name="invoices")
    branch          = models.ForeignKey(Branch, on_delete=models.PROTECT)
    invoice_number  = models.CharField(max_length=30, unique=True)
    status          = models.CharField(max_length=20, choices=STATUS_CHOICES, default="draft", db_index=True)
    subtotal        = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    tax_amount      = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    discount_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    total_amount    = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    paid_amount     = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    notes           = models.TextField(blank=True)
    created_by      = models.ForeignKey(StaffUser, on_delete=models.SET_NULL,
                                        null=True, blank=True)
    issued_at       = models.DateTimeField(null=True, blank=True)
    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

    class Meta:
        app_label = "billing"
        db_table  = "invoice"

    def __str__(self):
        return f"{self.invoice_number} — {self.patient.uhid} (₹{self.total_amount})"


class InvoiceItem(models.Model):
    invoice         = models.ForeignKey(Invoice, on_delete=models.CASCADE,
                                        related_name="items")
    service         = models.ForeignKey(BillingService, on_delete=models.PROTECT,
                                        null=True, blank=True)
    description     = models.CharField(max_length=200)  # denormalized
    quantity        = models.PositiveSmallIntegerField(default=1)
    unit_price      = models.DecimalField(max_digits=10, decimal_places=2)
    tax_rate        = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    total           = models.DecimalField(max_digits=12, decimal_places=2)

    class Meta:
        app_label = "billing"
        db_table  = "invoice_item"


class Payment(models.Model):
    """Payment record against an invoice. Multiple payments allowed (partial payments)."""
    PAYMENT_MODE_CHOICES = [
        ("cash",   "Cash"),
        ("card",   "Card"),
        ("upi",    "UPI"),
        ("online", "Online"),
        ("credit", "Credit"),
    ]

    invoice         = models.ForeignKey(Invoice, on_delete=models.PROTECT,
                                        related_name="payments")
    amount          = models.DecimalField(max_digits=12, decimal_places=2)
    payment_mode    = models.CharField(max_length=20, choices=PAYMENT_MODE_CHOICES)
    transaction_ref = models.CharField(max_length=100, blank=True)
    recorded_by     = models.ForeignKey(StaffUser, on_delete=models.SET_NULL, null=True)
    paid_at         = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "billing"
        db_table  = "payment"

    def __str__(self):
        return f"₹{self.amount} via {self.payment_mode} for {self.invoice.invoice_number}"
