"""
apps/billing/models.py
----------------------
Tables: BillingService (catalog), Invoice, InvoiceItem, Payment, OptionList
invoice_number generated by NNTM (entity="invoice").

OptionList (v7 redesign) replaces what used to be three near-identical
tables — ServiceCategory, PaymentModeOption, InvoiceStatusOption — plus
apps.prescriptions.DrugFormType, merged in via a `list_type` discriminator.
All four existed purely to replace hardcoded `choices=` lists with
tenant-managed, editable-via-UI lookup tables; none of them were DB-FK
enforced (BillingService.category / Payment.payment_mode / Invoice.status /
Drug.form are all plain CharFields, validated at the view/serializer layer
against these rows, not real foreign keys) — so collapsing them into one
table with a type column changes nothing about how they're consumed.
Seeded defaults are flagged is_system=True so the handful of values the
backend's own logic depends on (e.g. Invoice status "paid" driving payment
reconciliation) can't be deleted out from under it — they can still be
relabelled, and the hospital can always add their own custom entries
alongside them.

`value` vs `label`: for invoice_status, `value` is the actual code stored on
Invoice.status (e.g. "paid") and `label` is what's shown in the UI (e.g.
"Paid") — they can differ. For the other three list types there's no
separate stored code, so `value` is kept identical to `label` (both hold
e.g. "Cash") purely so a single (list_type, value) uniqueness constraint
can cover every list_type uniformly.
"""

from django.db import models
from apps.org.models import StaffUser, Branch
from apps.patients.models import Patient


class OptionList(models.Model):
    """Tenant-managed dropdown lists, merged across billing + pharmacy setup screens."""
    LIST_SERVICE_CATEGORY = "service_category"
    LIST_PAYMENT_MODE     = "payment_mode"
    LIST_INVOICE_STATUS   = "invoice_status"
    LIST_DRUG_FORM        = "drug_form"
    # Added for apps.ipd (Phase 1 admission intake) — admission_type and
    # admission_source are deliberately TWO separate catalogs (urgency vs.
    # how the patient arrived), not one. See apps/ipd/models.py module
    # docstring for why, and apps/ipd/migrations/0002_seed_admission_catalogs.py
    # for the seeded is_system=True defaults.
    LIST_ADMISSION_TYPE   = "admission_type"
    LIST_ADMISSION_SOURCE = "admission_source"
    LIST_TYPE_CHOICES = [
        (LIST_SERVICE_CATEGORY, "Service Category"),
        (LIST_PAYMENT_MODE, "Payment Mode"),
        (LIST_INVOICE_STATUS, "Invoice Status"),
        (LIST_DRUG_FORM, "Drug Form"),
        (LIST_ADMISSION_TYPE, "Admission Type"),
        (LIST_ADMISSION_SOURCE, "Admission Source"),
    ]

    list_type   = models.CharField(max_length=20, choices=LIST_TYPE_CHOICES, db_index=True)
    value       = models.CharField(max_length=20)   # what's actually stored/matched against
    label       = models.CharField(max_length=50)   # what's shown in the UI
    is_active   = models.BooleanField(default=True)
    is_system   = models.BooleanField(default=False)  # seeded default — can't be deleted
    sort_order  = models.PositiveSmallIntegerField(default=0)
    created_at  = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "billing"
        db_table  = "option_list"
        ordering  = ["list_type", "sort_order", "label"]
        constraints = [
            models.UniqueConstraint(fields=["list_type", "value"], name="uniq_option_list_type_value"),
        ]

    def __str__(self):
        return f"{self.list_type}:{self.label}"


class BillingService(models.Model):
    """Tenant-configured price list for services, procedures, etc."""
    name        = models.CharField(max_length=200)
    code        = models.CharField(max_length=50, blank=True)
    category    = models.CharField(max_length=50, default="Other")  # validated against OptionList(list_type="service_category"), not a DB choices= constraint
    unit_price  = models.DecimalField(max_digits=10, decimal_places=2)
    tax_rate    = models.DecimalField(max_digits=5, decimal_places=2, default=0)  # % — falls back to the tenant's default_tax_rate when omitted
    is_active   = models.BooleanField(default=True)
    created_at  = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "billing"
        db_table  = "billing_service"
        ordering  = ["name"]

    def __str__(self):
        return f"{self.name} (₹{self.unit_price})"


class Invoice(models.Model):
    # Kept as plain constants (not a `choices=` list) for internal logic to
    # reference — the actual set of valid values lives in
    # OptionList(list_type="invoice_status") now, validated at the view
    # layer, so a hospital can extend it.
    STATUS_DRAFT          = "draft"
    STATUS_ISSUED         = "issued"
    STATUS_PAID           = "paid"
    STATUS_PARTIALLY_PAID = "partially_paid"
    STATUS_CANCELLED      = "cancelled"

    patient         = models.ForeignKey(Patient, on_delete=models.PROTECT,
                                        related_name="invoices")
    # `encounter` (FK to apps.clinical.Encounter) was removed (HMS-07c-1) —
    # it was always left null in practice: the live OPD flow's
    # _auto_generate_invoice() (apps/opd/views.py) never set it, since
    # apps.clinical.Encounter and apps.opd.OPDEncounter are incompatible
    # types and the latter is what a real consultation actually creates.
    # apps.clinical.Encounter itself has since been retired entirely.
    branch          = models.ForeignKey(Branch, on_delete=models.PROTECT)
    invoice_number  = models.CharField(max_length=30, unique=True)
    status          = models.CharField(max_length=20, default=STATUS_DRAFT, db_index=True)  # validated against OptionList(list_type="invoice_status")
    subtotal        = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    tax_amount      = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    discount_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    total_amount    = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    paid_amount     = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    notes           = models.TextField(blank=True)
    created_by      = models.ForeignKey(StaffUser, on_delete=models.SET_NULL,
                                        null=True, blank=True)
    issued_at       = models.DateTimeField(null=True, blank=True)
    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

    class Meta:
        app_label = "billing"
        db_table  = "invoice"

    def __str__(self):
        return f"{self.invoice_number} — {self.patient.uhid} (₹{self.total_amount})"


class InvoiceItem(models.Model):
    invoice         = models.ForeignKey(Invoice, on_delete=models.CASCADE,
                                        related_name="items")
    service         = models.ForeignKey(BillingService, on_delete=models.PROTECT,
                                        null=True, blank=True)
    description     = models.CharField(max_length=200)  # denormalized
    quantity        = models.PositiveSmallIntegerField(default=1)
    unit_price      = models.DecimalField(max_digits=10, decimal_places=2)
    tax_rate        = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    total           = models.DecimalField(max_digits=12, decimal_places=2)

    class Meta:
        app_label = "billing"
        db_table  = "invoice_item"


class Payment(models.Model):
    """Payment record against an invoice. Multiple payments allowed (partial payments)."""
    invoice         = models.ForeignKey(Invoice, on_delete=models.PROTECT,
                                        related_name="payments")
    amount          = models.DecimalField(max_digits=12, decimal_places=2)
    payment_mode    = models.CharField(max_length=50)  # validated against OptionList(list_type="payment_mode"), not a DB choices= constraint
    transaction_ref = models.CharField(max_length=100, blank=True)
    recorded_by     = models.ForeignKey(StaffUser, on_delete=models.SET_NULL, null=True)
    paid_at         = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "billing"
        db_table  = "payment"

    def __str__(self):
        return f"₹{self.amount} via {self.payment_mode} for {self.invoice.invoice_number}"
