"""
apps/billing/models.py
----------------------
Tables: BillingService (catalog), Invoice, InvoiceItem, Payment,
        ServiceCategory, PaymentModeOption, InvoiceStatusOption
invoice_number generated by NNTM (entity="invoice").

ServiceCategory / PaymentModeOption / InvoiceStatusOption replace what used
to be hardcoded `choices=` lists — same pattern as
apps.prescriptions.DrugFormType for drug forms: tenant-managed, editable via
a Hospital Admin "Billing Setup" screen instead of baked into the model.
Seeded defaults are flagged is_system=True so the handful of values the
backend's own logic depends on (e.g. Invoice status "paid" driving payment
reconciliation) can't be deleted out from under it — they can still be
relabelled, and the hospital can always add their own custom entries
alongside them.
"""

from django.db import models
from apps.org.models import StaffUser, Branch
from apps.patients.models import Patient


class ServiceCategory(models.Model):
    """Configurable category list for the BillingService price catalog."""
    name        = models.CharField(max_length=50, unique=True)
    is_active   = models.BooleanField(default=True)
    is_system   = models.BooleanField(default=False)  # seeded default — can't be deleted
    sort_order  = models.PositiveSmallIntegerField(default=0)
    created_at  = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "billing"
        db_table  = "billing_service_category"
        ordering  = ["sort_order", "name"]

    def __str__(self):
        return self.name


class PaymentModeOption(models.Model):
    """Configurable list of accepted payment modes (cash/card/UPI/...)."""
    name        = models.CharField(max_length=50, unique=True)
    is_active   = models.BooleanField(default=True)
    is_system   = models.BooleanField(default=False)
    sort_order  = models.PositiveSmallIntegerField(default=0)
    created_at  = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "billing"
        db_table  = "billing_payment_mode"
        ordering  = ["sort_order", "name"]

    def __str__(self):
        return self.name


class InvoiceStatusOption(models.Model):
    """
    Configurable list of invoice statuses. "draft", "issued", "paid",
    "partially_paid", "cancelled" are seeded as is_system=True because
    PaymentCreateView's paid/partially_paid computation and
    InvoiceItemCreateView's draft/issued gate depend on those exact stored
    values existing — `value` can't change on a system row, only `label`.
    A hospital can add extra custom statuses (e.g. "Sent to Insurance") for
    their own tracking; those are purely informational, no automation is
    tied to them.
    """
    value       = models.CharField(max_length=20, unique=True)  # what's actually stored on Invoice.status
    label       = models.CharField(max_length=40)                # what's shown in the UI
    is_active   = models.BooleanField(default=True)
    is_system   = models.BooleanField(default=False)
    sort_order  = models.PositiveSmallIntegerField(default=0)
    created_at  = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "billing"
        db_table  = "billing_invoice_status"
        ordering  = ["sort_order", "label"]

    def __str__(self):
        return self.label


class BillingService(models.Model):
    """Tenant-configured price list for services, procedures, etc."""
    name        = models.CharField(max_length=200)
    code        = models.CharField(max_length=50, blank=True)
    category    = models.CharField(max_length=50, default="Other")  # validated against ServiceCategory, not a DB choices= constraint
    unit_price  = models.DecimalField(max_digits=10, decimal_places=2)
    tax_rate    = models.DecimalField(max_digits=5, decimal_places=2, default=0)  # % — falls back to the tenant's default_tax_rate when omitted
    is_active   = models.BooleanField(default=True)
    created_at  = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "billing"
        db_table  = "billing_service"
        ordering  = ["name"]

    def __str__(self):
        return f"{self.name} (₹{self.unit_price})"


class Invoice(models.Model):
    # Kept as plain constants (not a `choices=` list) for internal logic to
    # reference — the actual set of valid values lives in InvoiceStatusOption
    # now, validated at the view layer, so a hospital can extend it.
    STATUS_DRAFT          = "draft"
    STATUS_ISSUED         = "issued"
    STATUS_PAID           = "paid"
    STATUS_PARTIALLY_PAID = "partially_paid"
    STATUS_CANCELLED      = "cancelled"

    patient         = models.ForeignKey(Patient, on_delete=models.PROTECT,
                                        related_name="invoices")
    # `encounter` (FK to apps.clinical.Encounter) was removed (HMS-07c-1) —
    # it was always left null in practice: the live OPD flow's
    # _auto_generate_invoice() (apps/opd/views.py) never set it, since
    # apps.clinical.Encounter and apps.opd.OPDEncounter are incompatible
    # types and the latter is what a real consultation actually creates.
    # apps.clinical.Encounter itself has since been retired entirely.
    branch          = models.ForeignKey(Branch, on_delete=models.PROTECT)
    invoice_number  = models.CharField(max_length=30, unique=True)
    status          = models.CharField(max_length=20, default=STATUS_DRAFT, db_index=True)  # validated against InvoiceStatusOption
    subtotal        = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    tax_amount      = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    discount_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    total_amount    = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    paid_amount     = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    notes           = models.TextField(blank=True)
    created_by      = models.ForeignKey(StaffUser, on_delete=models.SET_NULL,
                                        null=True, blank=True)
    issued_at       = models.DateTimeField(null=True, blank=True)
    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

    class Meta:
        app_label = "billing"
        db_table  = "invoice"

    def __str__(self):
        return f"{self.invoice_number} — {self.patient.uhid} (₹{self.total_amount})"


class InvoiceItem(models.Model):
    invoice         = models.ForeignKey(Invoice, on_delete=models.CASCADE,
                                        related_name="items")
    service         = models.ForeignKey(BillingService, on_delete=models.PROTECT,
                                        null=True, blank=True)
    description     = models.CharField(max_length=200)  # denormalized
    quantity        = models.PositiveSmallIntegerField(default=1)
    unit_price      = models.DecimalField(max_digits=10, decimal_places=2)
    tax_rate        = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    total           = models.DecimalField(max_digits=12, decimal_places=2)

    class Meta:
        app_label = "billing"
        db_table  = "invoice_item"


class Payment(models.Model):
    """Payment record against an invoice. Multiple payments allowed (partial payments)."""
    invoice         = models.ForeignKey(Invoice, on_delete=models.PROTECT,
                                        related_name="payments")
    amount          = models.DecimalField(max_digits=12, decimal_places=2)
    payment_mode    = models.CharField(max_length=50)  # validated against PaymentModeOption, not a DB choices= constraint
    transaction_ref = models.CharField(max_length=100, blank=True)
    recorded_by     = models.ForeignKey(StaffUser, on_delete=models.SET_NULL, null=True)
    paid_at         = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "billing"
        db_table  = "payment"

    def __str__(self):
        return f"₹{self.amount} via {self.payment_mode} for {self.invoice.invoice_number}"
