# Generated by Django 4.2.13 on 2026-07-31 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subdomain', models.CharField(max_length=100, unique=True)),
                ('db_name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_tier', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('grace', 'Grace Period'), ('read_only', 'Read Only'), ('frozen', 'Frozen'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('trial_ends_on', models.DateField(blank=True, null=True)),
                ('current_period_start', models.DateField(blank=True, null=True)),
                ('current_period_end', models.DateField(blank=True, null=True)),
                ('payment_lapse_since', models.DateField(blank=True, null=True)),
                ('feat_lab', models.BooleanField(default=False)),
                ('feat_pharmacy', models.BooleanField(default=False)),
                ('feat_whatsapp', models.BooleanField(default=False)),
                ('feat_multi_branch', models.BooleanField(default=False)),
                ('feat_ai_voice', models.BooleanField(default=False)),
                ('feat_patient_app', models.BooleanField(default=False)),
                ('feat_analytics', models.BooleanField(default=False)),
                ('feat_video', models.BooleanField(default=False)),
                ('feat_face_recog', models.BooleanField(default=False)),
                ('max_doctors', models.PositiveIntegerField(default=3)),
                ('max_branches', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='NextNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField(db_index=True)),
                ('entity', models.CharField(max_length=20)),
                ('prefix', models.CharField(default='', max_length=10)),
                ('last_number', models.PositiveBigIntegerField(default=0)),
                ('pad_length', models.PositiveSmallIntegerField(default=6)),
            ],
            options={
                'db_table': 'next_number',
                'unique_together': {('branch_id', 'entity')},
            },
        ),
    ]
