# Generated by Django 4.2.13 on 2026-08-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='accreditations',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
