# Generated by Django 4.2.13 on 2026-08-06 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_about_tenant_accreditations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('tier_change', 'Tier Change'), ('status_change', 'Subscription Status Change'), ('active_change', 'Active/Suspended Toggle')], max_length=20)),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('before_value', models.CharField(blank=True, max_length=100)),
                ('after_value', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
