# Generated by Django 4.2.13 on 2026-08-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Hospital Created'), ('tier_change', 'Tier Change'), ('status_change', 'Subscription Status Change'), ('active_change', 'Active/Suspended Toggle')], max_length=20),
        ),
    ]
