# Generated by Django 4.2.13 on 2026-08-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenantauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='max_staff',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
