# Generated by Django 4.2.13 on 2026-08-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_subscription_max_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='feat_custom_roles',
            field=models.BooleanField(default=False),
        ),
    ]
