# Generated by Django 4.2.13 on 2026-08-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_subscription_feat_custom_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='active_vaccination_schedule_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
