# Generated by Django 4.2.13 on 2026-08-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_fee_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Hospital Created'), ('tier_change', 'Tier Change'), ('status_change', 'Subscription Status Change'), ('active_change', 'Active/Suspended Toggle'), ('subdomain_change', 'Hospital Code Change')], max_length=20),
        ),
    ]
