# Generated by Django 4.2.13 on 2026-08-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_alter_tenantauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='registration_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='registration_fee_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
