# Generated by Django 4.2.13 on 2026-08-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_default_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.TextField(blank=True),
        ),
    ]
