# Generated by Django 4.2.13 on 2026-08-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='storage_folder',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
