# Generated by Django 4.2.13 on 2026-09-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenant_storage_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='active_milestone_schedule_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
