# Generated by Django 4.2.13 on 2026-09-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenant_active_milestone_schedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
