# Generated by Django 4.2.13 on 2026-08-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_invoice_encounter'),
        ('ai_pipeline', '0003_remove_suggestionaudit_doctor_and_more'),
        # lab.LabRequest.encounter originally pointed at clinical.encounter;
        # lab/0003 repoints it to opd.opdencounter. Without this dependency,
        # nothing stops the planner from deleting Encounter (below) before
        # lab has created/repointed that FK, leaving a dangling string
        # reference that fails with "Related model 'clinical.encounter'
        # cannot be resolved" when the schema editor generates the FK
        # column SQL for lab.LabRequest.
        ('lab', '0003_labreport_file_name_labreport_mime_type_and_more'),
        # prescriptions.Prescription.encounter pointed at clinical.encounter
        # until the whole Prescription/PrescriptionItem model pair was
        # deleted in prescriptions/0004. Same class of bug as lab above —
        # Encounter must not be deleted before that FK's owning model is
        # gone.
        ('prescriptions', '0004_remove_prescriptionitem_drug_and_more'),
        ('clinical', '0002_alter_encounter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='encounter',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='department',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='encounter',
        ),
        migrations.RemoveField(
            model_name='vital',
            name='encounter',
        ),
        migrations.RemoveField(
            model_name='vital',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='vital',
            name='recorded_by',
        ),
        migrations.DeleteModel(
            name='ClinicalDocument',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Encounter',
        ),
        migrations.DeleteModel(
            name='FollowUp',
        ),
        migrations.DeleteModel(
            name='Vital',
        ),
    ]
