# Generated by Django 4.2.13 on 2026-08-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordamendment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved and Applied'), ('rejected', 'Rejected with Reason')], db_index=True, default='pending', max_length=20),
        ),
    ]
