# Generated by Django 4.2.13 on 2026-08-17 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0016_alter_auditlog_actor_user_id'),
        ('patients', '0007_patient_guardian_awpid_patient_guardian_mobile_and_more'),
        ('compliance', '0002_alter_recordamendment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('dpdp_data_processing', 'DPDP — Personal Data Processing'), ('hie_data_sharing', 'HIE — Cross-Hospital Data Sharing')], db_index=True, max_length=30)),
                ('granted', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('front_desk', 'Front Desk Registration'), ('patient_portal', 'Patient Portal')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('policy_version', models.CharField(default='v1', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.staffuser')),
            ],
            options={
                'db_table': 'consent_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AccessLog',
        ),
    ]
