"""
Management command: backfill_investor_demo_profiles

Retrofits an ALREADY-SEEDED seed_investor_demo tenant (e.g. Novacare
Hospital) with the profile detail that version of the seed script didn't
yet fill in: StaffUser.date_of_birth for every staff member (doctors
included), a full StaffProfile row for every non-doctor staff member
(qualification, experience, gender, bio, languages, and — for nurse/
pharmacist specifically — registration_no/council_name/registration_expiry),
and the Billing Setup "Service Price Catalog" (which nothing seeded at all).

This is a targeted backfill, not a re-seed: it never touches Tenant,
Branch, Doctor/Room/Schedule, or patient/appointment/invoice data, so it's
safe to run against a tenant that already has real demo activity on it
(the Novacare tenant this was written for has real invoices already).

It works by matching each existing StaffUser row (by role + first/last
name) against the same hand-authored DOCTORS / NURSE_NAMES / ... rosters
in seed_investor_demo.py, and reusing that command's own
_dob_for_age/_finish_staff logic — so the values here are generated by
the exact same code a fresh seed_investor_demo run would use, just applied
after the fact. A staff member added by hand after seeding (who isn't in
any of those rosters) is left untouched — there's no authored detail to
backfill them with.

Usage:
  python manage.py backfill_investor_demo_profiles --tenant aw_novacare_flagship --settings=atomwalk.settings.development
"""

import random
from decimal import Decimal

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction

from apps.tenants.models import Tenant
from apps.tenants.utils import _make_db_config
from apps.org.models import StaffUser
from apps.billing.models import BillingService

from apps.registry.management.commands.seed_investor_demo import (
    Command as SeedInvestorDemoCommand,
    DOCTORS, DOCTORS_B, NURSE_NAMES, FRONT_DESK_NAMES, LAB_TECH_NAMES, PHARMACIST_NAMES,
    ADMIN_NAMES, BILLING_CATALOG,
)


class Command(BaseCommand):
    help = ("Backfill date_of_birth + StaffProfile + billing service catalog "
            "for an already-seeded seed_investor_demo tenant.")

    def add_arguments(self, parser):
        parser.add_argument("--tenant", dest="db_name", required=True,
                             help="Tenant db_name to backfill (e.g. aw_novacare_flagship).")

    def handle(self, *args, **options):
        db = options["db_name"]

        try:
            tenant = Tenant.objects.using("default").get(db_name=db)
        except Tenant.DoesNotExist:
            raise CommandError(f"No tenant found with db_name='{db}'.")

        if db not in settings.DATABASES:
            settings.DATABASES[db] = _make_db_config(db)

        rng = random.Random(20260827)
        helper = SeedInvestorDemoCommand()
        language = f"English, Hindi, {helper._local_language(tenant.city)}"

        # role -> {(first.lower(), last.lower()): (gender, exp)}
        role_rosters = {
            "nurse":          {(f.lower(), l.lower()): (g, e) for f, l, g, e in NURSE_NAMES},
            "front_desk":     {(f.lower(), l.lower()): (g, e) for f, l, g, e in FRONT_DESK_NAMES},
            "lab_tech":       {(f.lower(), l.lower()): (g, e) for f, l, g, e in LAB_TECH_NAMES},
            "pharmacist":     {(f.lower(), l.lower()): (g, e) for f, l, g, e in PHARMACIST_NAMES},
            "hospital_admin": {(f.lower(), l.lower()): (g, e) for f, l, g, e in ADMIN_NAMES},
            # A tenant seeded with --roster b has doctors from DOCTORS_B, not
            # DOCTORS — merge both so this matches either roster regardless
            # of which one the tenant was originally seeded with.
            "doctor":         {(d["first"].lower(), d["last"].lower()): (d["gender"], d["exp"])
                                for d in (*DOCTORS, *DOCTORS_B)},
        }

        with transaction.atomic(using=db):
            matched, skipped = 0, []
            for staff in StaffUser.objects.using(db).filter(role__in=role_rosters.keys()):
                roster = role_rosters[staff.role]
                key = (staff.first_name.lower(), staff.last_name.lower())
                if key not in roster:
                    skipped.append(f"{staff.get_full_name()} ({staff.role})")
                    continue
                gender, exp = roster[key]
                helper._finish_staff(db, staff, staff.role, exp, gender, language, rng, tenant.name)
                matched += 1
                self.stdout.write(f"  {staff.get_full_name()} ({staff.role}) — DOB + profile set")

            self.stdout.write("  Seeding billing service price catalog...")
            catalog_added = 0
            for svc_name, svc_code, svc_category, svc_price in BILLING_CATALOG:
                _, created = BillingService.objects.using(db).get_or_create(
                    name=svc_name,
                    defaults={"code": svc_code, "category": svc_category,
                              "unit_price": Decimal(svc_price), "tax_rate": Decimal("0"), "is_active": True},
                )
                catalog_added += int(created)

        self.stdout.write(self.style.SUCCESS(
            f"\nDone — {matched} staff profile(s) backfilled, "
            f"{catalog_added} billing service(s) added."
        ))
        if skipped:
            self.stdout.write(self.style.WARNING(
                "Skipped (not in the original seed roster, no authored detail to backfill):\n  "
                + "\n  ".join(skipped)
            ))
