# Generated by Django 4.2.13 on 2026-08-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_auditlog_alter_nextnumber_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
