# Generated by Django 4.2.13 on 2026-08-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_doctorprofile_bio_doctorprofile_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='photo',
            field=models.TextField(blank=True),
        ),
    ]
