# Generated by Django 4.2.13 on 2026-08-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_staffuser_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(blank=True, max_length=50)),
                ('council_name', models.CharField(blank=True, max_length=150)),
                ('registration_expiry', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('bio', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, max_length=200)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='org.staffuser')),
            ],
            options={
                'db_table': 'staff_profile',
            },
        ),
    ]
