# Generated by Django 4.2.13 on 2026-08-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='known_for',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
