# Generated by Django 4.2.13 on 2026-08-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_doctorprofile_known_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
