# Generated by Django 4.2.13 on 2026-08-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_staffuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
