# Generated by Django 4.2.13 on 2026-08-07 05:38

from django.db import migrations, models
import django.db.models.deletion


def backfill_primary_branch_mappings(apps, schema_editor):
    """
    Every staff member who already has StaffUser.branch set gets one
    StaffBranchMapping row (is_primary=True) so the new table starts in
    sync with the legacy single-FK assignment nothing has to change for
    existing staff — this is purely additive.
    """
    StaffUser = apps.get_model("org", "StaffUser")
    StaffBranchMapping = apps.get_model("org", "StaffBranchMapping")
    db_alias = schema_editor.connection.alias
    mappings = [
        StaffBranchMapping(staff_id=s.id, branch_id=s.branch_id, is_primary=True)
        for s in StaffUser.objects.using(db_alias).filter(branch_id__isnull=False)
    ]
    if mappings:
        StaffBranchMapping.objects.using(db_alias).bulk_create(mappings, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    pass  # Nothing to undo — reversing the CreateModel below drops the table anyway.


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_alter_staffuser_email_alter_staffuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffBranchMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_mappings', to='org.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_mappings', to='org.staffuser')),
            ],
            options={
                'db_table': 'staff_branch_mapping',
            },
        ),
        migrations.AddConstraint(
            model_name='staffbranchmapping',
            constraint=models.UniqueConstraint(fields=('staff', 'branch'), name='uniq_staff_branch'),
        ),
        migrations.AddConstraint(
            model_name='staffbranchmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('staff',), name='uniq_staff_primary_branch'),
        ),
        migrations.RunPython(backfill_primary_branch_mappings, noop_reverse),
    ]
