# Generated by Django 4.2.13 on 2026-08-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_staffbranchmapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
