# Generated by Django 4.2.13 on 2026-08-07 06:10

from django.db import migrations, models
import django.db.models.deletion


def seed_permission_catalog_and_system_roles(apps, schema_editor):
    """
    Populate the permission catalog and the 6 system roles (+ their default
    grants) in this tenant DB, from apps.org.rbac's PERMISSION_CATALOG /
    SYSTEM_ROLE_PERMISSIONS / SYSTEM_ROLE_LABELS. Runs once per tenant DB,
    same as every other tenant-app migration. Purely additive — doesn't
    touch StaffUser.role or any existing permission check.
    """
    from apps.org.rbac import PERMISSION_CATALOG, SYSTEM_ROLE_PERMISSIONS, SYSTEM_ROLE_LABELS

    Permission = apps.get_model("org", "Permission")
    Role = apps.get_model("org", "Role")
    RolePermission = apps.get_model("org", "RolePermission")
    db = schema_editor.connection.alias

    code_to_perm = {}
    for code, description in PERMISSION_CATALOG.items():
        perm, _ = Permission.objects.using(db).get_or_create(
            code=code, defaults={"description": description}
        )
        code_to_perm[code] = perm

    for role_key, codes in SYSTEM_ROLE_PERMISSIONS.items():
        role, _ = Role.objects.using(db).get_or_create(
            system_role_key=role_key,
            defaults={
                "name": SYSTEM_ROLE_LABELS.get(role_key, role_key),
                "is_system_role": True,
            },
        )
        for code in codes:
            perm = code_to_perm.get(code)
            if perm:
                RolePermission.objects.using(db).get_or_create(role=role, permission=perm)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0012_staffuser_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'permission',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_system_role', models.BooleanField(default=False)),
                ('system_role_key', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'role',
                'ordering': ['-is_system_role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.role')),
            ],
            options={
                'db_table': 'role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='org.RolePermission', to='org.permission'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='org.role')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_roles', to='org.staffuser')),
            ],
            options={
                'db_table': 'user_role',
                'unique_together': {('staff', 'role')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name',)},
        ),
        migrations.RunPython(seed_permission_catalog_and_system_roles, noop_reverse),
    ]
