# Generated by Django 4.2.13 on 2026-08-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0015_room_roomassignment'),
    ]

    operations = [
        # Not a plain AlterField on purpose — Postgres has no implicit
        # uuid -> bigint cast, so "ALTER COLUMN ... TYPE bigint USING
        # actor_user_id::bigint" (what AlterField generates) always fails
        # with "cannot cast type uuid to bigint". There's nothing worth
        # preserving in the old column anyway: it was a UUIDField being fed
        # StaffUser's plain integer id (see the note on the field below and
        # apps/compliance/views.py), so every write of a real value was
        # already failing silently before this migration — the column only
        # ever held NULLs. Drop + recreate sidesteps the cast entirely.
        migrations.RemoveField(
            model_name='auditlog',
            name='actor_user_id',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_user_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
