# Generated by Django 4.2.13 on 2026-08-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0016_alter_auditlog_actor_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='followup_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
