# Generated by Django 4.2.13 on 2026-08-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0017_doctorprofile_followup_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='acts_as',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_staff', to='org.role'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('hospital_admin', 'Hospital Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('front_desk', 'Front Desk'), ('lab_tech', 'Lab Technician'), ('pharmacist', 'Pharmacist'), ('custom', 'Custom Role')], max_length=30),
        ),
    ]
