# Generated by Django 4.2.13 on 2026-08-27 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0018_role_acts_as_staff_custom_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseDoctorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_nurse_links', to='org.staffuser')),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'nurse'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_doctor_links', to='org.staffuser')),
            ],
            options={
                'db_table': 'nurse_doctor_assignment',
            },
        ),
        migrations.AddConstraint(
            model_name='nursedoctorassignment',
            constraint=models.UniqueConstraint(fields=('nurse', 'doctor'), name='uniq_nurse_doctor'),
        ),
    ]
