# Generated by Django 4.2.13 on 2026-09-15 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0019_nursedoctorassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ward_type', models.CharField(choices=[('general', 'General'), ('private', 'Private'), ('semi_private', 'Semi-Private'), ('icu', 'ICU'), ('hdu', 'HDU'), ('isolation', 'Isolation'), ('other', 'Other')], default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='org.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='org.department')),
            ],
            options={
                'db_table': 'ward',
                'ordering': ['name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('cleaning', 'Cleaning'), ('blocked', 'Blocked'), ('out_of_service', 'Out of Service')], db_index=True, default='available', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='org.ward')),
            ],
            options={
                'db_table': 'bed',
                'ordering': ['ward__name', 'bed_number'],
                'unique_together': {('ward', 'bed_number')},
            },
        ),
    ]
