# Generated by Django 4.2.13 on 2026-09-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0021_add_floor_and_ward_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='consultation', max_length=20),
        ),
    ]
