# Generated by hand — NOT run against a live database in this session
# (no DB reachable from here; run `python manage.py migrate_tenants` after
# pulling this change — mirrors 0022_room_type_drop_choices.py).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0022_room_type_drop_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='ward_type',
            field=models.CharField(default='general', max_length=20),
        ),
    ]
