# Generated by hand — NOT run against a live database in this session
# (no DB reachable from here; run `python manage.py migrate_tenants` after
# pulling this change).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0023_ward_type_drop_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
