# Generated by hand — NOT run against a live database in this session (no
# DB reachable from here; run `python manage.py migrate_tenants` after
# pulling this change).
#
# First step of folding org.Ward into org.Room (v8 unification — see
# org.Room's own docstring). Adds Bed.room as a NULLABLE FK so
# 0027_migrate_wards_to_rooms_and_beds can populate it from each Bed's
# existing `ward` before 0028 makes it required and drops `ward`/Ward
# entirely — splitting this into stages (add nullable -> backfill -> make
# required -> drop old) is what lets a hand-written migration carry real
# existing data (4 wards / 9 beds in the tenant this was developed against)
# through the schema change instead of just recreating empty tables.
#
# related_name="beds" here doesn't clash with Bed.ward's own
# related_name="beds" — they point at different target models (Room vs
# Ward), so `room.beds` and `ward.beds` are two distinct accessors.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0024_ward_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='org.room'),
        ),
    ]
