# Generated by hand — NOT run against a live database in this session (no
# DB reachable from here; run `python manage.py migrate_tenants` after
# pulling this change).
#
# Second step of folding org.Ward into org.Room — gives Room the two
# fields that used to live only on Ward (department, capacity) before
# 0027 copies each existing Ward's data across. Both nullable — an OPD
# room never sets either; capacity is enforced as required at the view
# layer (org.views.RoomListCreateView.post/RoomDetailView.patch) only when
# the room's type is bed-based, same as Ward.capacity's old comment said.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0025_bed_room_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='org.department'),
        ),
    ]
