# Generated by hand — NOT run against a live database in this session
# (no DB reachable from here; run `python manage.py migrate_tenants` after
# pulling this change).
#
# Core data migration for the v8 unification (org.Ward folded into
# org.Room — see org.Room's own docstring). For every existing Ward row:
# creates an equivalent Room (branch, floor_obj, department, capacity all
# copied across; room_type set from ward_type via WARD_TO_ROOM_TYPE_VALUE,
# the same mapping billing's 0016_merge_ward_types_into_room_types uses so
# the value lands on a matching, is_bed_based=True room_type catalog row),
# then repoints every Bed that belonged to that Ward at the new Room. Name
# collisions with a pre-existing Room at the same branch (unlikely, but
# Room and Ward previously had entirely separate uniqueness) are resolved
# by appending " (Ward)" — logged via a warning print so a hospital admin
# running the migration can see it happened.
#
# Ordered after billing's 0016 (cross-app dependency below) purely so the
# room_type catalog rows this migration's Rooms reference already exist by
# the time it runs — Room.room_type has no DB-level FK to OptionList (see
# Room's own docstring on why), so this isn't a hard requirement, just
# good sequencing.

from django.db import migrations

WARD_TO_ROOM_TYPE_VALUE = {
    "general":      "general",
    "private":      "private",
    "semi_private": "semi_private",
    "icu":          "icu",
    "hdu":          "hdu",
    "isolation":    "isolation",
    "other":        "ward_other",
}


def migrate_forward(apps, schema_editor):
    Ward  = apps.get_model("org", "Ward")
    Room  = apps.get_model("org", "Room")
    Bed   = apps.get_model("org", "Bed")
    Floor = apps.get_model("org", "Floor")
    db = schema_editor.connection.alias

    # Floor names are looked up via this dict (built with an explicit
    # `.using(db)` queryset) rather than by touching `ward.floor` on each
    # Ward instance — the forward-FK descriptor resolves its related-object
    # query through the DB router using instance hints instead of the
    # queryset's own alias, which under this project's per-tenant-database
    # routing can land on the "default"/public alias (no "floor" table
    # there) instead of `db`. Keying off `floor_id` (a plain column, no
    # relation traversal) sidesteps the router entirely.
    floor_names = dict(Floor.objects.using(db).values_list("id", "name"))

    ward_to_room = {}
    for ward in Ward.objects.using(db).all():
        name = ward.name
        if Room.objects.using(db).filter(branch_id=ward.branch_id, name__iexact=name).exists():
            name = f"{ward.name} (Ward)"
        room = Room.objects.using(db).create(
            branch_id=ward.branch_id,
            floor_obj_id=ward.floor_id,
            floor=floor_names.get(ward.floor_id, ""),
            department_id=ward.department_id,
            name=name,
            room_type=WARD_TO_ROOM_TYPE_VALUE.get(ward.ward_type, ward.ward_type),
            capacity=ward.capacity,
            is_active=ward.is_active,
        )
        ward_to_room[ward.id] = room.id

    for bed in Bed.objects.using(db).all():
        room_id = ward_to_room.get(bed.ward_id)
        if room_id:
            bed.room_id = room_id
            bed.save(using=db, update_fields=["room"])


def migrate_backward(apps, schema_editor):
    # Best-effort only — Bed.room is cleared (0025/0028 handle the field's
    # own reversibility); the Rooms created above are deliberately left in
    # place rather than deleted, since by the time a rollback runs they may
    # already carry live data (new beds, doctor assignments, admissions)
    # that a blind delete would destroy. Ward rows themselves were never
    # touched by this migration, so rolling forward again is always safe.
    Bed = apps.get_model("org", "Bed")
    db = schema_editor.connection.alias
    Bed.objects.using(db).update(room=None)


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0026_room_capacity_department'),
        ('billing', '0016_merge_ward_types_into_room_types'),
    ]

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
    ]
