# Generated by hand — NOT run against a live database in this session
# (no DB reachable from here; run `python manage.py migrate_tenants` after
# pulling this change).
#
# Final step of folding org.Ward into org.Room (v8 unification). By this
# point 0027 has already copied every Ward into an equivalent Room and
# repointed every Bed at it, so it's now safe to: make Bed.room required,
# swap Bed's unique_together/ordering from ward-based to room-based, drop
# Bed.ward, and drop the Ward model/table entirely.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0027_migrate_wards_to_rooms_and_beds'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'bed_number')},
        ),
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ['room__name', 'bed_number']},
        ),
        migrations.AlterField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='org.room'),
        ),
        migrations.RemoveField(
            model_name='bed',
            name='ward',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
