# Generated by Django 4.2.13 on 2026-09-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0028_finalize_bed_room_drop_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='reserved_for_admission_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('cleaning', 'Cleaning'), ('blocked', 'Blocked'), ('out_of_service', 'Out of Service')], db_index=True, default='available', max_length=15),
        ),
    ]
