# Generated by Django 4.2.13 on 2026-08-04 12:12
#
# NOTE: the RemoveField for "address" below is wrapped in
# SeparateDatabaseAndState with an empty database_operations list.
# Migration 0005 already dropped this column from the actual table via
# raw SQL (`DROP COLUMN IF EXISTS`) — this operation exists purely to
# catch Django's ORM model state up to that fact. Running the original
# Django-generated `ALTER TABLE "patient" DROP COLUMN "address"` here
# fails with "column does not exist" on any DB that already had 0005
# applied, which aborts the whole migration transaction (and blocks
# every migration after it, e.g. org's known_for) for that tenant.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_legacy_address'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='patient',
                    name='address',
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='patient',
            name='hie_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hie_consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationality',
            field=models.CharField(blank=True, default='Indian', max_length=50),
        ),
    ]
