# Generated by Django 4.2.13 on 2026-08-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_patient_address_patient_hie_consent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='guardian_awpid',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_dependent',
            field=models.BooleanField(default=False),
        ),
    ]
