# Generated by Django 4.2.13 on 2026-09-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_guardian_awpid_patient_guardian_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='arrival_channel',
            field=models.CharField(blank=True, choices=[('ambulance', 'Ambulance'), ('brought_in', 'Brought in'), ('police_case', 'Police case'), ('walk_in_unresponsive', 'Walk-in, unresponsive'), ('other', 'Other')], max_length=25),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_deferred_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='identity_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('provisional', 'Provisional')], default='confirmed', max_length=12),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_mlc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='placeholder_label',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
