# Generated by Django 4.2.13 on 2026-09-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_arrival_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestational_age_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('delivery_mode', models.CharField(blank=True, choices=[('normal', 'Normal Vaginal Delivery'), ('c_section', 'C-Section'), ('assisted', 'Assisted (Forceps/Vacuum)'), ('unknown', 'Unknown')], max_length=12)),
                ('multiple_birth', models.CharField(blank=True, max_length=50)),
                ('nicu_admission', models.BooleanField(default=False)),
                ('nicu_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_complications', models.TextField(blank=True)),
                ('congenital_conditions', models.TextField(blank=True)),
                ('apgar_score_1min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('apgar_score_5min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birth_history', to='patients.patient')),
            ],
            options={
                'db_table': 'birth_history',
            },
        ),
    ]
