# Generated by Django 4.2.13 on 2026-07-31 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0001_initial'),
        ('org', '0001_initial'),
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='org.branch')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='prescriptions.drug')),
            ],
            options={
                'db_table': 'stock',
                'unique_together': {('drug', 'branch', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('purchase', 'Purchase'), ('dispense', 'Dispense'), ('return', 'Return'), ('expiry', 'Expiry Write-off'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('quantity_before', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.staffuser')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='pharmacy.stock')),
            ],
            options={
                'db_table': 'stock_transaction',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationDoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('given', 'Given'), ('skipped', 'Skipped'), ('refused', 'Refused')], default='given', max_length=20)),
                ('administered_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('administered_by', models.ForeignKey(limit_choices_to={'role': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.staffuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dose_logs', to='prescriptions.prescriptionitem')),
            ],
            options={
                'db_table': 'medication_dose_log',
                'ordering': ['-administered_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('dispensed_by', models.ForeignKey(limit_choices_to={'role': 'pharmacist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.staffuser')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='prescriptions.prescriptionitem')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.stock')),
            ],
            options={
                'db_table': 'dispense',
            },
        ),
    ]
