# Generated by Django 4.2.13 on 2026-08-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationdoselog',
            name='status',
            field=models.CharField(choices=[('given', 'Given'), ('skipped', 'Skipped'), ('refused', 'Refused')], db_index=True, default='given', max_length=20),
        ),
    ]
