# Generated by Django 4.2.13 on 2026-08-17 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0008_appointment_floor_appointment_room_id_and_more'),
        ('pharmacy', '0002_alter_medicationdoselog_status'),
    ]

    operations = [
        # Not plain AlterFields on purpose — these repoint the FK from
        # prescriptions.PrescriptionItem (bigint PK) to opd.PrescriptionItem
        # (uuid PK). Postgres has no implicit bigint -> uuid cast, so the
        # "ALTER COLUMN ... TYPE uuid USING prescription_item_id::uuid" that
        # AlterField generates always fails with "cannot cast type bigint to
        # uuid". Nothing needs preserving here: prescriptions.PrescriptionItem
        # is legacy/dead scaffolding being retired in this same release (see
        # prescriptions/0004), so any existing values in these columns are
        # already pointing at a model on its way out. Drop + recreate
        # sidesteps the cast entirely, same fix as org/0016.
        migrations.RemoveField(
            model_name='dispense',
            name='prescription_item',
        ),
        migrations.AddField(
            model_name='dispense',
            name='prescription_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='opd.prescriptionitem'),
        ),
        migrations.RemoveField(
            model_name='medicationdoselog',
            name='prescription_item',
        ),
        migrations.AddField(
            model_name='medicationdoselog',
            name='prescription_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dose_logs', to='opd.prescriptionitem'),
        ),
    ]
