# Generated by Django 4.2.13 on 2026-09-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationlog_read_at_notificationlog_reference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='template',
        ),
        migrations.DeleteModel(
            name='DeviceToken',
        ),
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
    ]
